In [29]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML

# Import data

In [30]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 0.5, "long_term": 0.1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,0.50,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.49,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.48,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.47,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.46,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [31]:
df_matrix_mf = df.copy()
df_matrix_mf = df_matrix_mf[df["type"] == "top_track"]
df_matrix_mf["username"] = df_matrix_mf["username"].astype("category")
df_matrix_mf["id"] = df_matrix_mf["id"].astype("category")
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100
df_matrix_mf["affinity"]

0        50.0
1        49.0
2        48.0
3        47.0
4        46.0
         ...
12318     1.0
12319     0.8
12320     0.6
12321     0.4
12322     0.2
Name: affinity, Length: 1200, dtype: float64

In [32]:
# Create the matrix dataset
class MatrixDataset:
    _matrix: np.ndarray

    @property
    def matrix(self) -> np.ndarray:
        return self._matrix

    def __init__(self, num_users: int, num_items: int):
        # A matrix of shape (num_users, num_items)
        self._matrix = np.zeros((num_users, num_items))

    def add_interaction(self, user_id: int, item_id: int, value: float):
        """
        Adds a new interaction to the matrix.
        :param user_id: The user id.
        :param item_id: The item id.
        :param value: The value of the interaction.
        """
        self._matrix[user_id, item_id] = value

    def fill_from_df(self, users: pd.Series, items: pd.Series, values: pd.Series):
        """
        Fills the matrix from a dataframe.
        :param df: The dataframe.
        :param user_col: The user column.
        :param item_col: The item column.
        :param value_col: The value column.
        """
        assert (
            len(users) == len(items) == len(values)
        ), "The length of the users, items and values must be the same."

        for user, item, value in zip(users, items, values):
            self.add_interaction(user, item, value)

    def __str__(self):
        return str(self._matrix)

In [33]:
num_users = len(df_matrix_mf["username"].unique())
num_items = len(df_matrix_mf["id"].unique())

In [34]:
matrix_mf = MatrixDataset(num_users, num_items)
matrix_mf.fill_from_df(df_matrix_mf["username"].cat.codes, df_matrix_mf["id"].cat.codes, df_matrix_mf["affinity"])
R = matrix_mf.matrix
R

array([[ 0. ,  0. , 62. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 54. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 4.4, 30. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ..., 46. ,  0. ,  0. ]])

In [35]:
def convert_to_ids(values: List[str], column: str) -> List[int]:
    """
    Gets the user ids from the usernames.
    :param usernames: The usernames.
    :return: The user ids.
    """
    return df_matrix_mf[df_matrix_mf[column].isin(values)][column].cat.codes.tolist()

def retrieve_value_from_ids(ids: List[int], column: str) -> str:
    """
    Gets the value from the ids.
    :param ids: The ids.
    :return: The value.
    """
    return df_matrix_mf[df_matrix_mf[column].cat.codes.isin(ids)][column].tolist()

def get_df_rows_from_ids(ids: List[int], column: str, search_in: pd.DataFrame) -> pd.DataFrame:
    """
    Gets the dataframe rows from the ids.
    :param ids: The ids.
    :return: The dataframe rows.
    """
    return search_in[search_in[column].cat.codes.isin(ids)]

In [36]:
# Create a matrix U that contains the index that sorts the users by their affinity
I = np.argsort(matrix_mf.matrix, axis=1)
I.shape

(8, 923)

In [37]:
def compute_alpha(matrix: np.ndarray) -> np.ndarray:
    """
    Computes the alpha matrix.
    :param matrix: The matrix.
    :param k: The number of neighbors.
    :return: The alpha matrix.
    """
    num_items = matrix.shape[1] * matrix.shape[0]
    sum_matrix = matrix.flatten().sum()
    number_of_zeros = num_items - np.count_nonzero(matrix)
    alpha = number_of_zeros / sum_matrix
    return alpha

alpha = compute_alpha(matrix_mf.matrix)
print(alpha)
R *= alpha
R

0.264317361339022

array([[ 0.        ,  0.        , 16.3876764 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 14.27313751],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.16299639,  7.92952084,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ..., 12.15859862,
         0.        ,  0.        ]])

_Let $l_{u,i}$ denote the event that user $u$ has chosen to interact with item $i$ (user $u$ prefers item $i$). Then, we can let the probability of this event occurring be distributed according to a logistic function parameterized by the sum of the inner product of user and item latent factor vectors and user and item biases._
$$
p(l_{ui} | x_u, y_i, \beta_i, \beta_j) = \frac{\exp(x_uy_i^T + \beta_u + \beta_i)}{1 + \exp(x_uy_i^T + \beta_u + \beta_i)}
$$

The log posterior probability of $x_u, y_i, \beta_u, \beta_i$ given the observed data $\mathbf{R}$ is given by:
$$
\log p(\mathbf{X}, \mathbf{Y}, \beta | \mathbf{R}) = \sum_{u,i} \alpha r_{ui} (x_u^T y_i + \beta_u + \beta_i) - (1 + \alpha r_{ui}) \log(1 + \exp(x_u^T y_i + \beta_u + \beta_i)) - \frac{\lambda}{2} ||x_u||^2 - \frac{\lambda}{2} ||y_i||^2
$$

In [38]:
def log_posterior(
    X: torch.Tensor,
    Y: torch.Tensor,
    beta_u: torch.Tensor,
    beta_i: torch.Tensor,
    R: torch.Tensor,
    alpha: float,
    lambd: float,
) -> torch.Tensor:
    """
    Computes the log posterior of the model, which is:
    :param X: The latent vectors of the users.
    :param Y: The latent vectors of the items.
    :param beta_u: The bias of the users.
    :param beta_i: The bias of the items.
    :param R: The matrix of interactions.
    :param alpha: The alpha parameter.
    :param lambd: The lambda parameter.
    :return: The log posterior.
    """
    # Compute the first term
    term1 = alpha * R * (torch.matmul(X, Y.t()) + beta_u[:, None] + beta_i)
    term2 = (1 + alpha * R) * torch.log1p(torch.exp(torch.matmul(X, Y.t()) + beta_u[:, None] + beta_i))
    regularization = (lambd / 2) * (torch.norm(X, p=2) ** 2 + torch.norm(Y, p=2) ** 2)
    return torch.sum(term1 - term2) - regularization

In [39]:
def mpr(I: torch.Tensor, R: torch.Tensor) -> float:
    """
    Compute the Mean Percentile Ranking (MPR) using a sorted index matrix.

    :param I: Matrix of sorted indices of items for each user.
    :param R: Rating or interaction matrix.
    :return: MPR value.
    """
    num_users, num_items = R.shape
    total_interactions = torch.sum(R)

    # Initialize MPR
    mpr = 0.0

    # Iterate over each user
    for u in range(num_users):
        # Get the indices of the items in sorted order for this user
        sorted_indices = I[u]

        # Calculate the rank for each item
        for i in range(num_items):
            item_index = sorted_indices[i]
            rank = i / num_items  # Percentile rank
            mpr += R[u, item_index] * rank

    # Normalize by the total number of interactions
    mpr /= total_interactions

    return mpr

In [40]:
def compute_predictions(
    X: torch.Tensor,
    Y: torch.Tensor,
    beta_u: torch.Tensor,
    beta_i: torch.Tensor,
) -> torch.Tensor:
    """
    Computes the predictions of the model.
    :param X: The latent vectors of the users.
    :param Y: The latent vectors of the items.
    :param beta_u: The bias of the users.
    :param beta_i: The bias of the items.
    :param R: The matrix of interactions.
    :return: The predictions.
    """
    return torch.matmul(X, Y.t()) + beta_u[:, None] + beta_i

In [41]:
def train(
    num_latent: int,
    lambd: float,
    alpha: float,
    learning_rate: float,
    epochs: int,
):
    """
    Trains the model.
    :param num_latent: The number of latent factors.
    :param lambd: The lambda parameter.
    :param alpha: The alpha parameter.
    :param learning_rate: The learning rate.
    :param epochs: The number of epochs.
    """
    mprs = []  # Record MPRs for each epoch
    losses = []  # Record losses for each epoch

    # Initialize user and item latent factor matrices and bias vectors
    R = torch.tensor(matrix_mf.matrix, dtype=torch.float32)
    X = torch.randn(num_users, num_latent, requires_grad=True)
    Y = torch.randn(num_items, num_latent, requires_grad=True)
    beta_u = torch.randn(num_users, requires_grad=True)
    beta_i = torch.randn(num_items, requires_grad=True)

    # The objective is to minimize the negative log posterior
    optimizer = optim.Adagrad([X, Y, beta_u, beta_i], lr=learning_rate)

    # Training loop
    for epoch in tqdm(range(epochs)):
        # Fix X and B and take a step toward Y and B
        X.requires_grad = False
        Y.requires_grad = True
        beta_u.requires_grad = False
        beta_i.requires_grad = True
        optimizer.zero_grad()
        loss = -log_posterior(X, Y, beta_u, beta_i, R, alpha, lambd)
        loss.backward()
        optimizer.step()

        # Fix Y and B and take a step toward X and B
        X.requires_grad = True
        Y.requires_grad = False
        beta_u.requires_grad = True
        beta_i.requires_grad = False
        optimizer.zero_grad()
        loss = -log_posterior(X, Y, beta_u, beta_i, R, alpha, lambd)
        loss.backward()
        optimizer.step()

        # Make predictions
        predictions = compute_predictions(X, Y, beta_u, beta_i)

        # Compute MPR
        I = torch.argsort(predictions, descending=True, dim=1)
        mpr_value = mpr(I, R)

        # Record MPR
        mprs.append(mpr_value)

        # Record loss
        losses.append(loss.item())

        # Print progress
        print(f"Epoch {epoch + 1} - Loss: {loss.item():.4f} - MPR: {mpr_value:.4f}")

    return X, Y, beta_u, beta_i, mprs, losses

In [42]:
num_latent = 100
X, Y, beta_u, beta_i, mprs, losses = train(
    num_latent=num_latent,
    lambd=0.00,
    alpha=alpha,
    learning_rate=0.1,
    epochs=300,
)

  1%|          | 2/300 [00:00<00:17, 16.94it/s]

Epoch 1 - Loss: 22938.0547 - MPR: 0.3467
Epoch 2 - Loss: 13523.7295 - MPR: 0.2499

  1%|▏         | 4/300 [00:00<00:16, 17.76it/s]

Epoch 3 - Loss: 8478.7676 - MPR: 0.1782
Epoch 4 - Loss: 5634.6465 - MPR: 0.1282

  2%|▏         | 6/300 [00:00<00:16, 18.05it/s]

Epoch 5 - Loss: 3990.5767 - MPR: 0.0926
Epoch 6 - Loss: 3007.6260 - MPR: 0.0712

  3%|▎         | 8/300 [00:00<00:16, 18.17it/s]

Epoch 7 - Loss: 2437.6172 - MPR: 0.0561
Epoch 8 - Loss: 2078.4487 - MPR: 0.0464

  3%|▎         | 10/300 [00:00<00:15, 18.25it/s]

Epoch 9 - Loss: 1870.8512 - MPR: 0.0398
Epoch 10 - Loss: 1734.7758 - MPR: 0.0363

  4%|▍         | 12/300 [00:00<00:15, 18.16it/s]

Epoch 11 - Loss: 1653.7815 - MPR: 0.0339
Epoch 12 - Loss: 1592.8569 - MPR: 0.0327

  5%|▍         | 14/300 [00:00<00:15, 18.13it/s]

Epoch 13 - Loss: 1551.9663 - MPR: 0.0315
Epoch 14 - Loss: 1519.0579 - MPR: 0.0307

  5%|▌         | 16/300 [00:00<00:15, 18.14it/s]

Epoch 15 - Loss: 1498.5408 - MPR: 0.0301
Epoch 16 - Loss: 1482.0654 - MPR: 0.0300

  6%|▌         | 18/300 [00:00<00:15, 18.21it/s]

Epoch 17 - Loss: 1470.6957 - MPR: 0.0296
Epoch 18 - Loss: 1460.5635 - MPR: 0.0296

  7%|▋         | 20/300 [00:01<00:15, 18.29it/s]

Epoch 19 - Loss: 1453.5918 - MPR: 0.0293
Epoch 20 - Loss: 1447.0874 - MPR: 0.0294

  7%|▋         | 22/300 [00:01<00:15, 18.33it/s]

Epoch 21 - Loss: 1442.5568 - MPR: 0.0291
Epoch 22 - Loss: 1437.6257 - MPR: 0.0292

  8%|▊         | 24/300 [00:01<00:15, 18.36it/s]

Epoch 23 - Loss: 1434.2274 - MPR: 0.0290
Epoch 24 - Loss: 1430.3727 - MPR: 0.0291

  9%|▊         | 26/300 [00:01<00:15, 17.88it/s]

Epoch 25 - Loss: 1427.6252 - MPR: 0.0289
Epoch 26 - Loss: 1424.6562 - MPR: 0.0290

  9%|▉         | 28/300 [00:01<00:15, 17.96it/s]

Epoch 27 - Loss: 1422.4124 - MPR: 0.0289
Epoch 28 - Loss: 1420.0555 - MPR: 0.0289

 10%|█         | 30/300 [00:01<00:15, 17.90it/s]

Epoch 29 - Loss: 1418.1877 - MPR: 0.0288
Epoch 30 - Loss: 1416.2627 - MPR: 0.0288

 11%|█         | 32/300 [00:01<00:14, 18.02it/s]

Epoch 31 - Loss: 1414.6797 - MPR: 0.0287
Epoch 32 - Loss: 1413.0767 - MPR: 0.0287

 11%|█▏        | 34/300 [00:01<00:14, 18.12it/s]

Epoch 33 - Loss: 1411.7253 - MPR: 0.0287
Epoch 34 - Loss: 1410.3783 - MPR: 0.0287

 12%|█▏        | 36/300 [00:01<00:14, 18.24it/s]

Epoch 35 - Loss: 1409.2258 - MPR: 0.0286
Epoch 36 - Loss: 1408.0966 - MPR: 0.0287

 13%|█▎        | 38/300 [00:02<00:14, 18.28it/s]

Epoch 37 - Loss: 1407.1169 - MPR: 0.0286
Epoch 38 - Loss: 1406.1702 - MPR: 0.0286

 13%|█▎        | 40/300 [00:02<00:14, 18.36it/s]

Epoch 39 - Loss: 1405.3275 - MPR: 0.0286
Epoch 40 - Loss: 1404.5203 - MPR: 0.0286

 14%|█▍        | 42/300 [00:02<00:14, 18.37it/s]

Epoch 41 - Loss: 1403.7811 - MPR: 0.0286
Epoch 42 - Loss: 1403.0775 - MPR: 0.0286

 15%|█▍        | 44/300 [00:02<00:14, 18.26it/s]

Epoch 43 - Loss: 1402.4200 - MPR: 0.0286
Epoch 44 - Loss: 1401.7955 - MPR: 0.0286

 15%|█▌        | 46/300 [00:02<00:13, 18.22it/s]

Epoch 45 - Loss: 1401.2063 - MPR: 0.0286
Epoch 46 - Loss: 1400.6469 - MPR: 0.0286

 16%|█▌        | 48/300 [00:02<00:14, 17.34it/s]

Epoch 47 - Loss: 1400.1180 - MPR: 0.0286
Epoch 48 - Loss: 1399.6150 - MPR: 0.0286

 17%|█▋        | 50/300 [00:02<00:14, 17.70it/s]

Epoch 49 - Loss: 1399.1404 - MPR: 0.0285
Epoch 50 - Loss: 1398.6879 - MPR: 0.0286

 17%|█▋        | 52/300 [00:02<00:13, 17.87it/s]

Epoch 51 - Loss: 1398.2617 - MPR: 0.0285
Epoch 52 - Loss: 1397.8531 - MPR: 0.0285

 18%|█▊        | 54/300 [00:02<00:13, 18.04it/s]

Epoch 53 - Loss: 1397.4691 - MPR: 0.0285
Epoch 54 - Loss: 1397.0991 - MPR: 0.0285

 19%|█▊        | 56/300 [00:03<00:13, 18.21it/s]

Epoch 55 - Loss: 1396.7516 - MPR: 0.0285
Epoch 56 - Loss: 1396.4146 - MPR: 0.0285

 19%|█▉        | 58/300 [00:03<00:13, 18.33it/s]

Epoch 57 - Loss: 1396.0986 - MPR: 0.0285
Epoch 58 - Loss: 1395.7902 - MPR: 0.0285

 20%|██        | 60/300 [00:03<00:13, 18.43it/s]

Epoch 59 - Loss: 1395.5015 - MPR: 0.0285
Epoch 60 - Loss: 1395.2179 - MPR: 0.0285

 21%|██        | 62/300 [00:03<00:12, 18.48it/s]

Epoch 61 - Loss: 1394.9530 - MPR: 0.0285
Epoch 62 - Loss: 1394.6908 - MPR: 0.0285

 21%|██▏       | 64/300 [00:03<00:12, 18.48it/s]

Epoch 63 - Loss: 1394.4474 - MPR: 0.0285
Epoch 64 - Loss: 1394.2041 - MPR: 0.0285

 22%|██▏       | 66/300 [00:03<00:12, 18.51it/s]

Epoch 65 - Loss: 1393.9799 - MPR: 0.0285
Epoch 66 - Loss: 1393.7534 - MPR: 0.0285

 23%|██▎       | 68/300 [00:03<00:12, 17.99it/s]

Epoch 67 - Loss: 1393.5466 - MPR: 0.0285
Epoch 68 - Loss: 1393.3354 - MPR: 0.0285

 23%|██▎       | 70/300 [00:03<00:12, 18.18it/s]

Epoch 69 - Loss: 1393.1443 - MPR: 0.0285
Epoch 70 - Loss: 1392.9473 - MPR: 0.0285

 24%|██▍       | 72/300 [00:03<00:12, 18.37it/s]

Epoch 71 - Loss: 1392.7698 - MPR: 0.0285
Epoch 72 - Loss: 1392.5859 - MPR: 0.0285

 25%|██▍       | 74/300 [00:04<00:12, 18.42it/s]

Epoch 73 - Loss: 1392.4210 - MPR: 0.0285
Epoch 74 - Loss: 1392.2495 - MPR: 0.0285

 25%|██▌       | 76/300 [00:04<00:12, 18.52it/s]

Epoch 75 - Loss: 1392.0956 - MPR: 0.0285
Epoch 76 - Loss: 1391.9354 - MPR: 0.0285

 26%|██▌       | 78/300 [00:04<00:11, 18.59it/s]

Epoch 77 - Loss: 1391.7911 - MPR: 0.0285
Epoch 78 - Loss: 1391.6414 - MPR: 0.0285

 27%|██▋       | 80/300 [00:04<00:11, 18.63it/s]

Epoch 79 - Loss: 1391.5060 - MPR: 0.0285
Epoch 80 - Loss: 1391.3656 - MPR: 0.0285

 27%|██▋       | 82/300 [00:04<00:11, 18.66it/s]

Epoch 81 - Loss: 1391.2380 - MPR: 0.0285
Epoch 82 - Loss: 1391.1060 - MPR: 0.0285

 28%|██▊       | 84/300 [00:04<00:11, 18.63it/s]

Epoch 83 - Loss: 1390.9862 - MPR: 0.0285
Epoch 84 - Loss: 1390.8616 - MPR: 0.0285

 29%|██▊       | 86/300 [00:04<00:11, 18.61it/s]

Epoch 85 - Loss: 1390.7491 - MPR: 0.0285
Epoch 86 - Loss: 1390.6311 - MPR: 0.0285

 29%|██▉       | 88/300 [00:04<00:11, 18.68it/s]

Epoch 87 - Loss: 1390.5261 - MPR: 0.0285
Epoch 88 - Loss: 1390.4138 - MPR: 0.0285

 30%|███       | 90/300 [00:04<00:11, 18.37it/s]

Epoch 89 - Loss: 1390.3173 - MPR: 0.0285
Epoch 90 - Loss: 1390.2098 - MPR: 0.0285

 31%|███       | 92/300 [00:05<00:11, 18.35it/s]

Epoch 91 - Loss: 1390.1218 - MPR: 0.0285
Epoch 92 - Loss: 1390.0189 - MPR: 0.0285

 31%|███▏      | 94/300 [00:05<00:11, 18.20it/s]

Epoch 93 - Loss: 1389.9401 - MPR: 0.0285
Epoch 94 - Loss: 1389.8405 - MPR: 0.0285

 32%|███▏      | 96/300 [00:05<00:11, 18.12it/s]

Epoch 95 - Loss: 1389.7715 - MPR: 0.0285
Epoch 96 - Loss: 1389.6733 - MPR: 0.0285

 33%|███▎      | 98/300 [00:05<00:11, 18.24it/s]

Epoch 97 - Loss: 1389.6130 - MPR: 0.0285
Epoch 98 - Loss: 1389.5143 - MPR: 0.0285

 33%|███▎      | 100/300 [00:05<00:10, 18.27it/s]

Epoch 99 - Loss: 1389.4609 - MPR: 0.0285
Epoch 100 - Loss: 1389.3583 - MPR: 0.0285

 34%|███▍      | 102/300 [00:05<00:10, 18.42it/s]

Epoch 101 - Loss: 1389.3090 - MPR: 0.0285
Epoch 102 - Loss: 1389.2012 - MPR: 0.0285

 35%|███▍      | 104/300 [00:05<00:10, 18.39it/s]

Epoch 103 - Loss: 1389.1526 - MPR: 0.0285
Epoch 104 - Loss: 1389.0410 - MPR: 0.0285

 35%|███▌      | 106/300 [00:05<00:10, 18.43it/s]

Epoch 105 - Loss: 1388.9911 - MPR: 0.0285
Epoch 106 - Loss: 1388.8777 - MPR: 0.0285

 36%|███▌      | 108/300 [00:05<00:10, 18.50it/s]

Epoch 107 - Loss: 1388.8251 - MPR: 0.0285
Epoch 108 - Loss: 1388.7130 - MPR: 0.0285

 37%|███▋      | 110/300 [00:06<00:10, 18.61it/s]

Epoch 109 - Loss: 1388.6578 - MPR: 0.0285
Epoch 110 - Loss: 1388.5491 - MPR: 0.0285

 37%|███▋      | 112/300 [00:06<00:10, 18.42it/s]

Epoch 111 - Loss: 1388.4917 - MPR: 0.0285
Epoch 112 - Loss: 1388.3876 - MPR: 0.0285

 38%|███▊      | 114/300 [00:06<00:10, 18.47it/s]

Epoch 113 - Loss: 1388.3280 - MPR: 0.0285
Epoch 114 - Loss: 1388.2291 - MPR: 0.0285

 39%|███▊      | 116/300 [00:06<00:09, 18.54it/s]

Epoch 115 - Loss: 1388.1683 - MPR: 0.0285
Epoch 116 - Loss: 1388.0747 - MPR: 0.0285

 39%|███▉      | 118/300 [00:06<00:09, 18.56it/s]

Epoch 117 - Loss: 1388.0131 - MPR: 0.0285
Epoch 118 - Loss: 1387.9247 - MPR: 0.0285

 40%|████      | 120/300 [00:06<00:09, 18.63it/s]

Epoch 119 - Loss: 1387.8622 - MPR: 0.0285
Epoch 120 - Loss: 1387.7792 - MPR: 0.0285

 41%|████      | 122/300 [00:06<00:09, 18.68it/s]

Epoch 121 - Loss: 1387.7166 - MPR: 0.0285
Epoch 122 - Loss: 1387.6388 - MPR: 0.0285

 41%|████▏     | 124/300 [00:06<00:09, 18.73it/s]

Epoch 123 - Loss: 1387.5763 - MPR: 0.0285
Epoch 124 - Loss: 1387.5035 - MPR: 0.0285

 42%|████▏     | 126/300 [00:06<00:09, 18.76it/s]

Epoch 125 - Loss: 1387.4415 - MPR: 0.0285
Epoch 126 - Loss: 1387.3738 - MPR: 0.0285

 43%|████▎     | 128/300 [00:06<00:09, 18.80it/s]

Epoch 127 - Loss: 1387.3126 - MPR: 0.0285
Epoch 128 - Loss: 1387.2502 - MPR: 0.0285

 43%|████▎     | 130/300 [00:07<00:09, 18.59it/s]

Epoch 129 - Loss: 1387.1902 - MPR: 0.0285
Epoch 130 - Loss: 1387.1328 - MPR: 0.0285

 44%|████▍     | 132/300 [00:07<00:09, 18.46it/s]

Epoch 131 - Loss: 1387.0740 - MPR: 0.0285
Epoch 132 - Loss: 1387.0217 - MPR: 0.0285

 45%|████▍     | 134/300 [00:07<00:08, 18.49it/s]

Epoch 133 - Loss: 1386.9650 - MPR: 0.0285
Epoch 134 - Loss: 1386.9177 - MPR: 0.0285

 45%|████▌     | 136/300 [00:07<00:08, 18.56it/s]

Epoch 135 - Loss: 1386.8625 - MPR: 0.0285
Epoch 136 - Loss: 1386.8201 - MPR: 0.0285

 46%|████▌     | 138/300 [00:07<00:08, 18.60it/s]

Epoch 137 - Loss: 1386.7665 - MPR: 0.0285
Epoch 138 - Loss: 1386.7285 - MPR: 0.0285

 47%|████▋     | 140/300 [00:07<00:08, 18.65it/s]

Epoch 139 - Loss: 1386.6768 - MPR: 0.0285
Epoch 140 - Loss: 1386.6428 - MPR: 0.0285

 47%|████▋     | 142/300 [00:07<00:08, 18.66it/s]

Epoch 141 - Loss: 1386.5930 - MPR: 0.0285
Epoch 142 - Loss: 1386.5624 - MPR: 0.0285

 48%|████▊     | 144/300 [00:07<00:08, 18.69it/s]

Epoch 143 - Loss: 1386.5145 - MPR: 0.0285
Epoch 144 - Loss: 1386.4869 - MPR: 0.0285

 49%|████▊     | 146/300 [00:07<00:08, 18.75it/s]

Epoch 145 - Loss: 1386.4412 - MPR: 0.0285
Epoch 146 - Loss: 1386.4161 - MPR: 0.0285

 49%|████▉     | 148/300 [00:08<00:08, 18.67it/s]

Epoch 147 - Loss: 1386.3726 - MPR: 0.0285
Epoch 148 - Loss: 1386.3492 - MPR: 0.0285

 50%|█████     | 150/300 [00:08<00:08, 18.53it/s]

Epoch 149 - Loss: 1386.3083 - MPR: 0.0285
Epoch 150 - Loss: 1386.2864 - MPR: 0.0285

 51%|█████     | 152/300 [00:08<00:08, 17.40it/s]

Epoch 151 - Loss: 1386.2476 - MPR: 0.0285
Epoch 152 - Loss: 1386.2257 - MPR: 0.0285

 51%|█████▏    | 154/300 [00:08<00:08, 17.73it/s]

Epoch 153 - Loss: 1386.1892 - MPR: 0.0285
Epoch 154 - Loss: 1386.1667 - MPR: 0.0285

 52%|█████▏    | 156/300 [00:08<00:07, 18.00it/s]

Epoch 155 - Loss: 1386.1315 - MPR: 0.0285
Epoch 156 - Loss: 1386.1077 - MPR: 0.0285

 53%|█████▎    | 158/300 [00:08<00:07, 18.20it/s]

Epoch 157 - Loss: 1386.0737 - MPR: 0.0285
Epoch 158 - Loss: 1386.0476 - MPR: 0.0285

 53%|█████▎    | 160/300 [00:08<00:07, 18.27it/s]

Epoch 159 - Loss: 1386.0143 - MPR: 0.0285
Epoch 160 - Loss: 1385.9855 - MPR: 0.0285

 54%|█████▍    | 162/300 [00:08<00:07, 18.38it/s]

Epoch 161 - Loss: 1385.9525 - MPR: 0.0285
Epoch 162 - Loss: 1385.9208 - MPR: 0.0285

 55%|█████▍    | 164/300 [00:08<00:07, 18.47it/s]

Epoch 163 - Loss: 1385.8882 - MPR: 0.0285
Epoch 164 - Loss: 1385.8538 - MPR: 0.0285

 55%|█████▌    | 166/300 [00:09<00:07, 18.54it/s]

Epoch 165 - Loss: 1385.8217 - MPR: 0.0285
Epoch 166 - Loss: 1385.7850 - MPR: 0.0285

 56%|█████▌    | 168/300 [00:09<00:07, 18.64it/s]

Epoch 167 - Loss: 1385.7534 - MPR: 0.0285
Epoch 168 - Loss: 1385.7152 - MPR: 0.0285

 57%|█████▋    | 170/300 [00:09<00:06, 18.65it/s]

Epoch 169 - Loss: 1385.6847 - MPR: 0.0285
Epoch 170 - Loss: 1385.6453 - MPR: 0.0285

 57%|█████▋    | 172/300 [00:09<00:06, 18.44it/s]

Epoch 171 - Loss: 1385.6161 - MPR: 0.0285
Epoch 172 - Loss: 1385.5762 - MPR: 0.0285

 58%|█████▊    | 174/300 [00:09<00:06, 18.49it/s]

Epoch 173 - Loss: 1385.5481 - MPR: 0.0285
Epoch 174 - Loss: 1385.5077 - MPR: 0.0285

 59%|█████▊    | 176/300 [00:09<00:06, 18.57it/s]

Epoch 175 - Loss: 1385.4812 - MPR: 0.0285
Epoch 176 - Loss: 1385.4408 - MPR: 0.0285

 59%|█████▉    | 178/300 [00:09<00:06, 18.62it/s]

Epoch 177 - Loss: 1385.4156 - MPR: 0.0285
Epoch 178 - Loss: 1385.3755 - MPR: 0.0285

 60%|██████    | 180/300 [00:09<00:06, 18.67it/s]

Epoch 179 - Loss: 1385.3511 - MPR: 0.0285
Epoch 180 - Loss: 1385.3114 - MPR: 0.0285

 61%|██████    | 182/300 [00:09<00:06, 18.70it/s]

Epoch 181 - Loss: 1385.2880 - MPR: 0.0285
Epoch 182 - Loss: 1385.2488 - MPR: 0.0285

 61%|██████▏   | 184/300 [00:10<00:06, 18.64it/s]

Epoch 183 - Loss: 1385.2256 - MPR: 0.0285
Epoch 184 - Loss: 1385.1869 - MPR: 0.0285

 62%|██████▏   | 186/300 [00:10<00:06, 18.69it/s]

Epoch 185 - Loss: 1385.1639 - MPR: 0.0285
Epoch 186 - Loss: 1385.1260 - MPR: 0.0285

 63%|██████▎   | 188/300 [00:10<00:05, 18.74it/s]

Epoch 187 - Loss: 1385.1027 - MPR: 0.0285
Epoch 188 - Loss: 1385.0653 - MPR: 0.0285

 63%|██████▎   | 190/300 [00:10<00:05, 18.76it/s]

Epoch 189 - Loss: 1385.0417 - MPR: 0.0285
Epoch 190 - Loss: 1385.0050 - MPR: 0.0285

 64%|██████▍   | 192/300 [00:10<00:05, 18.27it/s]

Epoch 191 - Loss: 1384.9808 - MPR: 0.0285
Epoch 192 - Loss: 1384.9448 - MPR: 0.0285

 65%|██████▍   | 194/300 [00:10<00:05, 18.31it/s]

Epoch 193 - Loss: 1384.9202 - MPR: 0.0285
Epoch 194 - Loss: 1384.8850 - MPR: 0.0285

 65%|██████▌   | 196/300 [00:10<00:05, 18.43it/s]

Epoch 195 - Loss: 1384.8596 - MPR: 0.0285
Epoch 196 - Loss: 1384.8252 - MPR: 0.0285

 66%|██████▌   | 198/300 [00:10<00:05, 18.50it/s]

Epoch 197 - Loss: 1384.7997 - MPR: 0.0285
Epoch 198 - Loss: 1384.7659 - MPR: 0.0285

 67%|██████▋   | 200/300 [00:10<00:05, 18.60it/s]

Epoch 199 - Loss: 1384.7402 - MPR: 0.0285
Epoch 200 - Loss: 1384.7076 - MPR: 0.0285

 67%|██████▋   | 202/300 [00:10<00:05, 18.51it/s]

Epoch 201 - Loss: 1384.6820 - MPR: 0.0285
Epoch 202 - Loss: 1384.6501 - MPR: 0.0285

 68%|██████▊   | 204/300 [00:11<00:05, 18.54it/s]

Epoch 203 - Loss: 1384.6251 - MPR: 0.0285
Epoch 204 - Loss: 1384.5945 - MPR: 0.0285

 69%|██████▊   | 206/300 [00:11<00:05, 18.54it/s]

Epoch 205 - Loss: 1384.5698 - MPR: 0.0285
Epoch 206 - Loss: 1384.5403 - MPR: 0.0285

 69%|██████▉   | 208/300 [00:11<00:04, 18.59it/s]

Epoch 207 - Loss: 1384.5165 - MPR: 0.0285
Epoch 208 - Loss: 1384.4882 - MPR: 0.0285

 70%|███████   | 210/300 [00:11<00:04, 18.60it/s]

Epoch 209 - Loss: 1384.4650 - MPR: 0.0285
Epoch 210 - Loss: 1384.4377 - MPR: 0.0285

 71%|███████   | 212/300 [00:11<00:04, 18.06it/s]

Epoch 211 - Loss: 1384.4155 - MPR: 0.0285
Epoch 212 - Loss: 1384.3896 - MPR: 0.0285

 71%|███████▏  | 214/300 [00:11<00:04, 18.26it/s]

Epoch 213 - Loss: 1384.3683 - MPR: 0.0285
Epoch 214 - Loss: 1384.3433 - MPR: 0.0285

 72%|███████▏  | 216/300 [00:11<00:04, 18.40it/s]

Epoch 215 - Loss: 1384.3229 - MPR: 0.0285
Epoch 216 - Loss: 1384.2990 - MPR: 0.0285

 73%|███████▎  | 218/300 [00:11<00:04, 18.49it/s]

Epoch 217 - Loss: 1384.2794 - MPR: 0.0285
Epoch 218 - Loss: 1384.2566 - MPR: 0.0285

 73%|███████▎  | 220/300 [00:11<00:04, 18.48it/s]

Epoch 219 - Loss: 1384.2379 - MPR: 0.0285
Epoch 220 - Loss: 1384.2159 - MPR: 0.0285

 74%|███████▍  | 222/300 [00:12<00:04, 18.52it/s]

Epoch 221 - Loss: 1384.1980 - MPR: 0.0285
Epoch 222 - Loss: 1384.1768 - MPR: 0.0285

 75%|███████▍  | 224/300 [00:12<00:04, 18.60it/s]

Epoch 223 - Loss: 1384.1598 - MPR: 0.0285
Epoch 224 - Loss: 1384.1392 - MPR: 0.0285

 75%|███████▌  | 226/300 [00:12<00:03, 18.62it/s]

Epoch 225 - Loss: 1384.1228 - MPR: 0.0285
Epoch 226 - Loss: 1384.1028 - MPR: 0.0285

 76%|███████▌  | 228/300 [00:12<00:03, 18.67it/s]

Epoch 227 - Loss: 1384.0874 - MPR: 0.0285
Epoch 228 - Loss: 1384.0679 - MPR: 0.0285

 77%|███████▋  | 230/300 [00:12<00:03, 18.22it/s]

Epoch 229 - Loss: 1384.0530 - MPR: 0.0285
Epoch 230 - Loss: 1384.0341 - MPR: 0.0285

 77%|███████▋  | 232/300 [00:12<00:03, 18.31it/s]

Epoch 231 - Loss: 1384.0195 - MPR: 0.0285
Epoch 232 - Loss: 1384.0010 - MPR: 0.0285

 78%|███████▊  | 234/300 [00:12<00:03, 18.41it/s]

Epoch 233 - Loss: 1383.9873 - MPR: 0.0285
Epoch 234 - Loss: 1383.9691 - MPR: 0.0285

 79%|███████▊  | 236/300 [00:12<00:03, 18.58it/s]

Epoch 235 - Loss: 1383.9558 - MPR: 0.0285
Epoch 236 - Loss: 1383.9380 - MPR: 0.0285

 79%|███████▉  | 238/300 [00:12<00:03, 18.57it/s]

Epoch 237 - Loss: 1383.9252 - MPR: 0.0285
Epoch 238 - Loss: 1383.9075 - MPR: 0.0285

 80%|████████  | 240/300 [00:13<00:03, 18.64it/s]

Epoch 239 - Loss: 1383.8953 - MPR: 0.0285
Epoch 240 - Loss: 1383.8779 - MPR: 0.0285

 81%|████████  | 242/300 [00:13<00:03, 18.69it/s]

Epoch 241 - Loss: 1383.8662 - MPR: 0.0285
Epoch 242 - Loss: 1383.8490 - MPR: 0.0285

 81%|████████▏ | 244/300 [00:13<00:02, 18.70it/s]

Epoch 243 - Loss: 1383.8374 - MPR: 0.0285
Epoch 244 - Loss: 1383.8206 - MPR: 0.0285

 82%|████████▏ | 246/300 [00:13<00:02, 18.73it/s]

Epoch 245 - Loss: 1383.8093 - MPR: 0.0285
Epoch 246 - Loss: 1383.7927 - MPR: 0.0285

 83%|████████▎ | 248/300 [00:13<00:02, 18.70it/s]

Epoch 247 - Loss: 1383.7820 - MPR: 0.0285
Epoch 248 - Loss: 1383.7655 - MPR: 0.0285

 83%|████████▎ | 250/300 [00:13<00:02, 18.34it/s]

Epoch 249 - Loss: 1383.7551 - MPR: 0.0285
Epoch 250 - Loss: 1383.7386 - MPR: 0.0285

 84%|████████▍ | 252/300 [00:13<00:02, 18.41it/s]

Epoch 251 - Loss: 1383.7285 - MPR: 0.0285
Epoch 252 - Loss: 1383.7123 - MPR: 0.0285

 85%|████████▍ | 254/300 [00:13<00:02, 18.46it/s]

Epoch 253 - Loss: 1383.7024 - MPR: 0.0285
Epoch 254 - Loss: 1383.6862 - MPR: 0.0285

 85%|████████▌ | 256/300 [00:13<00:02, 18.47it/s]

Epoch 255 - Loss: 1383.6765 - MPR: 0.0285
Epoch 256 - Loss: 1383.6604 - MPR: 0.0285

 86%|████████▌ | 258/300 [00:14<00:02, 18.45it/s]

Epoch 257 - Loss: 1383.6510 - MPR: 0.0285
Epoch 258 - Loss: 1383.6350 - MPR: 0.0285

 87%|████████▋ | 260/300 [00:14<00:02, 18.41it/s]

Epoch 259 - Loss: 1383.6257 - MPR: 0.0285
Epoch 260 - Loss: 1383.6099 - MPR: 0.0285

 87%|████████▋ | 262/300 [00:14<00:02, 18.40it/s]

Epoch 261 - Loss: 1383.6006 - MPR: 0.0285
Epoch 262 - Loss: 1383.5847 - MPR: 0.0285

 88%|████████▊ | 264/300 [00:14<00:01, 18.47it/s]

Epoch 263 - Loss: 1383.5757 - MPR: 0.0285
Epoch 264 - Loss: 1383.5599 - MPR: 0.0285

 89%|████████▊ | 266/300 [00:14<00:01, 18.61it/s]

Epoch 265 - Loss: 1383.5507 - MPR: 0.0285
Epoch 266 - Loss: 1383.5349 - MPR: 0.0285

 89%|████████▉ | 268/300 [00:14<00:01, 17.75it/s]

Epoch 267 - Loss: 1383.5259 - MPR: 0.0285
Epoch 268 - Loss: 1383.5103 - MPR: 0.0285

 90%|█████████ | 270/300 [00:14<00:01, 18.05it/s]

Epoch 269 - Loss: 1383.5011 - MPR: 0.0285
Epoch 270 - Loss: 1383.4858 - MPR: 0.0285

 91%|█████████ | 272/300 [00:14<00:01, 18.28it/s]

Epoch 271 - Loss: 1383.4766 - MPR: 0.0285
Epoch 272 - Loss: 1383.4615 - MPR: 0.0285

 91%|█████████▏| 274/300 [00:14<00:01, 18.41it/s]

Epoch 273 - Loss: 1383.4520 - MPR: 0.0285
Epoch 274 - Loss: 1383.4370 - MPR: 0.0285

 92%|█████████▏| 276/300 [00:15<00:01, 18.52it/s]

Epoch 275 - Loss: 1383.4277 - MPR: 0.0285
Epoch 276 - Loss: 1383.4132 - MPR: 0.0285

 93%|█████████▎| 278/300 [00:15<00:01, 18.53it/s]

Epoch 277 - Loss: 1383.4037 - MPR: 0.0285
Epoch 278 - Loss: 1383.3895 - MPR: 0.0285

 93%|█████████▎| 280/300 [00:15<00:01, 18.58it/s]

Epoch 279 - Loss: 1383.3799 - MPR: 0.0285
Epoch 280 - Loss: 1383.3663 - MPR: 0.0285

 94%|█████████▍| 282/300 [00:15<00:00, 18.67it/s]

Epoch 281 - Loss: 1383.3564 - MPR: 0.0285
Epoch 282 - Loss: 1383.3435 - MPR: 0.0285

 95%|█████████▍| 284/300 [00:15<00:00, 18.71it/s]

Epoch 283 - Loss: 1383.3336 - MPR: 0.0285
Epoch 284 - Loss: 1383.3210 - MPR: 0.0285

 95%|█████████▌| 286/300 [00:15<00:00, 17.85it/s]

Epoch 285 - Loss: 1383.3114 - MPR: 0.0285
Epoch 286 - Loss: 1383.2991 - MPR: 0.0285

 96%|█████████▌| 288/300 [00:15<00:00, 18.13it/s]

Epoch 287 - Loss: 1383.2896 - MPR: 0.0285
Epoch 288 - Loss: 1383.2778 - MPR: 0.0285

 97%|█████████▋| 290/300 [00:15<00:00, 18.34it/s]

Epoch 289 - Loss: 1383.2682 - MPR: 0.0285
Epoch 290 - Loss: 1383.2568 - MPR: 0.0285

 97%|█████████▋| 292/300 [00:15<00:00, 18.46it/s]

Epoch 291 - Loss: 1383.2474 - MPR: 0.0285
Epoch 292 - Loss: 1383.2366 - MPR: 0.0285

 98%|█████████▊| 294/300 [00:15<00:00, 18.57it/s]

Epoch 293 - Loss: 1383.2272 - MPR: 0.0285
Epoch 294 - Loss: 1383.2167 - MPR: 0.0285

 99%|█████████▊| 296/300 [00:16<00:00, 18.60it/s]

Epoch 295 - Loss: 1383.2073 - MPR: 0.0285
Epoch 296 - Loss: 1383.1973 - MPR: 0.0285

 99%|█████████▉| 298/300 [00:16<00:00, 18.69it/s]

Epoch 297 - Loss: 1383.1882 - MPR: 0.0285
Epoch 298 - Loss: 1383.1783 - MPR: 0.0285

100%|██████████| 300/300 [00:16<00:00, 18.40it/s]

Epoch 299 - Loss: 1383.1694 - MPR: 0.0285
Epoch 300 - Loss: 1383.1597 - MPR: 0.0285

In [43]:
px.line(y=mprs, title="MPR over epochs").show()
px.line(y=losses, title="Loss over epochs").show()

In [44]:
user_latent = X.detach().numpy()
item_latent = Y.detach().numpy()

In [45]:
if num_latent <= 3:
    # Add the latent vectors to the dataframe
    df_matrix_mf["user_latent"] = df_matrix_mf["username"].cat.codes.apply(
        lambda x: user_latent[x]
    )
    df_matrix_mf["item_latent"] = df_matrix_mf["id"].cat.codes.apply(
        lambda x: item_latent[x]
    )

    # Add the biases to the dataframe
    df_matrix_mf["user_bias"] = df_matrix_mf["username"].cat.codes.apply(
        lambda x: beta_u[x].item()
    )
    df_matrix_mf["item_bias"] = df_matrix_mf["id"].cat.codes.apply(
        lambda x: beta_i[x].item()
    )

    for i in range(num_latent):
        df_matrix_mf[f"user_latent_{i}"] = df_matrix_mf["user_latent"].apply(lambda x: x[i])
        df_matrix_mf[f"latent_{i}"] = df_matrix_mf["item_latent"].apply(lambda x: x[i])

    fig = plotting.plot_latent_space(
        df_matrix_mf,
        color=df_matrix_mf["username"],
        text=df_matrix_mf["username"],
        title="User latent space",
        latent_columns=["latent_0", "latent_1", "latent_2"],
    )
    fig.show()

    df_user_latent = df_matrix_mf.drop_duplicates(subset=["username"])
    fig = plotting.plot_latent_space(
        df_user_latent,
        color=df_user_latent["username"],
        text=df_user_latent["username"],
        title="User latent space",
        latent_columns=["user_latent_0", "user_latent_1", "user_latent_2"],
    )
    fig.show()

In [46]:
def get_recommendations(user_id, X, Y, user_item_matrix, top_n=10):
    """
    Generate top-N item recommendations for a given user.

    :param user_id: The ID of the user for whom to generate recommendations.
    :param X: User factor matrix from Logistic MF.
    :param Y: Item factor matrix from Logistic MF.
    :param user_item_matrix: Original user-item interaction matrix.
    :param top_n: Number of top recommendations to return (default 10).
    :return: List of recommended item IDs, sorted by predicted preference.
    """

    # Check if user_id is valid
    if user_id >= X.shape[0]:
        raise ValueError("User ID is out of range.")

    # Compute predicted scores for all items for this user
    user_vector = X[user_id]
    predicted_scores = np.dot(user_vector, Y.T)

    # Filter out items the user has already interacted with
    known_items = user_item_matrix[user_id].nonzero()[0]
    predicted_scores[known_items] = -np.inf

    # Get indices of top-n items
    recommended_items = np.argsort(predicted_scores)[::-1][:top_n]

    return recommended_items

In [49]:
# Choose a user
user = "michelle"
user_id = convert_to_ids([user], "username")[0]

# Make predictions for the user
predictions = compute_predictions(X, Y, beta_u, beta_i)

# Get the indices of the top 10 recommendations
top_n = 20
recommendations = get_recommendations(user_id, X.detach().numpy(), Y.detach().numpy(), matrix_mf.matrix, top_n=top_n)
recommendations

# Get the top 10 recommendations
top_n_recommendations = retrieve_value_from_ids(recommendations, "id")
top_n_recommendations = get_df_rows_from_ids(recommendations, "id", df_matrix_mf)
top_n_recommendations[spoti.PRETTY_PRINT_FEATURES]

,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
6,jaslkh,ROSALÍA,CHICKEN TERIYAKI,2022,65,0.788,0.4000,0.1150,0.45400,0.000141,0.0686,0.5580,97.936,-6.454,122226,2022,65
26,jaslkh,St Graal,Drag,2023,41,0.666,0.6090,0.0575,0.13900,0.000000,0.0783,0.5840,112.979,-6.580,161333,2023,41
76,jaslkh,Frédéric Chopin,"Chopin: Nocturne No. 20 in C-Sharp Minor, Op. ...",2000,69,0.225,0.0047,0.0509,0.99200,0.881000,0.0722,0.1860,163.665,-30.928,259493,2000,69
90,jaslkh,Gloria Gaynor,I Will Survive,2012,50,0.648,0.6480,0.0444,0.03720,0.000000,0.2380,0.4060,119.270,-11.528,198653,2012,50
112,jaslkh,Fleetwood Mac,Dreams - 2004 Remaster,1977,89,0.828,0.4920,0.0276,0.06440,0.004280,0.1280,0.7890,120.151,-9.744,257800,1977,89
1604,owen,Dinos,93 mesures,2020,57,0.859,0.5290,0.3290,0.04850,0.000000,0.0965,0.3010,95.986,-9.899,265786,2020,57
1625,owen,Dinos,93 mesures,2020,57,0.859,0.5290,0.3290,0.04850,0.000000,0.0965,0.3010,95.986,-9.899,265786,2020,57
6991,brenda,Videoclub,Amour plastique,2021,65,0.696,0.3540,0.0353,0.76700,0.001580,0.1280,0.2420,119.938,-14.043,227026,2021,65
7030,brenda,Videoclub,Amour plastique,2021,65,0.696,0.3540,0.0353,0.76700,0.001580,0.1280,0.2420,119.938,-14.043,227026,2021,65
7109,brenda,Dalida,Gigi l'amoroso,1997,53,0.524,0.4330,0.0631,0.59800,0.000000,0.6150,0.6870,96.994,-8.880,448906,1997,53
7387,arthur,M83,Laura,2023,46,0.418,0.6890,0.0287,0.00319,0.122000,0.0946,0.2230,143.883,-5.694,248133,2023,46
7453,arthur,Romeo Santos,Odio (feat. Drake),2014,77,0.802,0.7250,0.0676,0.57400,0.000000,0.0821,0.5980,128.040,-5.965,225000,2014,77
7455,arthur,M83,Laura,2023,46,0.418,0.6890,0.0287,0.00319,0.122000,0.0946,0.2230,143.883,-5.694,248133,2023,46
7477,arthur,M83,Laura,2023,46,0.418,0.6890,0.0287,0.00319,0.122000,0.0946,0.2230,143.883,-5.694,248133,2023,46
7526,arthur,KronoMuzik,Dig Dig Deep Deep,2022,39,0.666,0.8480,0.0760,0.02870,0.002990,0.0557,0.9030,100.067,-8.429,135571,2022,39
10219,paul,Ateyaba,Moonwalk,2020,40,0.683,0.7050,0.1390,0.61100,0.003280,0.1430,0.1850,139.984,-6.925,203694,2020,40
10238,paul,Out of Townerz,Bleu Cheese,2020,37,0.844,0.8030,0.2840,0.11200,0.000000,0.1190,0.1100,109.972,-6.295,203051,2020,37
10242,paul,Gazo,DIE,2022,75,0.695,0.6300,0.0350,0.22900,0.000000,0.1180,0.5500,130.968,-7.160,240413,2022,75
10252,paul,A$AP Rocky,Lord Pretty Flacko Jodye 2 (LPFJ2),2015,75,0.485,0.7200,0.1270,0.01230,0.000000,0.0546,0.0471,207.982,-5.991,126960,2015,75
11387,lsirwguhu,Imagine Dragons,Thunder,2017,87,0.605,0.8220,0.0438,0.00671,0.134000,0.1470,0.2880,167.997,-4.833,187146,2017,87
11388,lsirwguhu,Calvin Harris,"Feels (feat. Pharrell Williams, Katy Perry & B...",2017,78,0.893,0.7450,0.0571,0.06420,0.000000,0.0943,0.8720,101.018,-3.105,223413,2017,78
12211,dany,David Gilmour,The Great Gig in the Sky - Live At Pompeii 2016,2017,39,0.252,0.2680,0.0466,0.85300,0.044000,0.8060,0.1360,120.457,-13.401,362986,2017,39
12216,dany,Dawid Podsiadło,Szarość i Róż,2022,51,0.553,0.6580,0.0320,0.04680,0.000112,0.0836,0.5770,172.028,-6.116,221293,2022,51
12236,dany,Gazo,DIE,2022,75,0.695,0.6300,0.0350,0.22900,0.000000,0.1180,0.5500,130.968,-7.160,240413,2022,75
12256,dany,Petit Biscuit,Wake Up,2017,46,0.580,0.5710,0.0908,0.12800,0.000006,0.0789,0.3580,91.069,-6.933,192440,2017,46