In [20]:
from constants import users_list, data_path
from lib import spoti, genre_normalizer, plotting, preprocessing, dimensionality_reduction

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.decomposition import PCA
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from sklearn.metrics import mean_squared_error
import random
import time
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors, NeighborhoodComponentsAnalysis
from sklearn.metrics import pairwise_distances
import pickle
import numpy as np
from typing import List, Dict, Tuple, Optional, Any, Callable
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from IPython.display import display, HTML

# Import data

In [21]:
df = spoti.load_all_tracks(
    base_path=data_path.DATA_PATH,
    users=users_list.USERS,
    load_spotify_tracks=False,
    penality_factors={"short_term": 1, "medium_term": 0.5, "long_term": 0.1},
)
df

,album,artists,available_markets,disc_number,duration_ms,explicit,external_ids,external_urls,href,id,...,time_range,affinity,username,release_year,normalized_genres,added_at,episode,track,added_by,playlist_id
0,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,196426,False,{'isrc': 'USSM12301260'},{'spotify': 'https://open.spotify.com/track/75...,https://api.spotify.com/v1/tracks/75rqqKvzJCGv...,75rqqKvzJCGv2oq9C4yFDt,...,medium_term,0.50,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
1,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,137533,True,{'isrc': 'USSM12109218'},{'spotify': 'https://open.spotify.com/track/2F...,https://api.spotify.com/v1/tracks/2FYGZDfsAnNs...,2FYGZDfsAnNsrm1gVbyKnG,...,medium_term,0.49,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
2,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,162906,True,{'isrc': 'USSM12109222'},{'spotify': 'https://open.spotify.com/track/4k...,https://api.spotify.com/v1/tracks/4kroNlz8BTfs...,4kroNlz8BTfswE4M0i3YCh,...,medium_term,0.48,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
3,"{'album_type': 'ALBUM', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,89749,False,{'isrc': 'USSM12208854'},{'spotify': 'https://open.spotify.com/track/2N...,https://api.spotify.com/v1/tracks/2N3YZ075lq9z...,2N3YZ075lq9z1ObaAiX6l1,...,medium_term,0.47,jaslkh,2022,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
4,"{'album_type': 'SINGLE', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AE, AR, AT, AU, BE, BG, BH, BO, BR, CA, C...",1,174044,False,{'isrc': 'USSM12300114'},{'spotify': 'https://open.spotify.com/track/2S...,https://api.spotify.com/v1/tracks/2SiAcexM2p1y...,2SiAcexM2p1yX6joESbehd,...,medium_term,0.46,jaslkh,2023,"[spanish, pop, rnb]",NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12424,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, BY, CH, CW, C...",1,251880,False,{'isrc': 'GBN9Y1100001'},{'spotify': 'https://open.spotify.com/track/3z...,https://api.spotify.com/v1/tracks/3z7dWKRsjDNM...,3z7dWKRsjDNM24ohLKZBnA,...,NaN,NaN,dany,1967,"[rock, rock, rock, rock, rock, rock, rock]",2022-12-30 08:42:31+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12425,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,193853,False,{'isrc': 'GBLTP1700005'},{'spotify': 'https://open.spotify.com/track/1V...,https://api.spotify.com/v1/tracks/1VofMhhL98pe...,1VofMhhL98pewltVGBSmCW,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:07+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12426,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,295493,False,{'isrc': 'GBLTP1700011'},{'spotify': 'https://open.spotify.com/track/0K...,https://api.spotify.com/v1/tracks/0KE7apgczHNY...,0KE7apgczHNYiXIvMUY0Fc,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:13+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12427,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,467306,False,{'isrc': 'GBLTP1700014'},{'spotify': 'https://open.spotify.com/track/6v...,https://api.spotify.com/v1/tracks/6vbRA9yAAgIX...,6vbRA9yAAgIXtDlmhyNqPq,...,NaN,NaN,dany,2017,"[rock, rock, rock, rock, rock]",2020-08-10 14:53:18+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9
12428,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AD, AL, AM, AT, AZ, BA, BE, BG, CH, CW, CY, C...",1,233760,False,{'isrc': 'GBLTP0600001'},{'spotify': 'https://open.spotify.com/track/0Y...,https://api.spotify.com/v1/tracks/0YFt5l6xOLbJ...,0YFt5l6xOLbJSJvyVZDpvX,...,NaN,NaN,dany,2006,"[rock, rock, rock, rock, rock]",2020-10-31 10:49:39+00:00,False,True,ssscnm71jg9pv7fryho4d5qgs,674vFKUXNUjlUxXhAnQvG9

# Logistic Matrix Factorization for Implicit Feedback Data (Logistic MF)
From [Christopher C. Johnson - Logistic Matrix Factorization for Implicit Feedback Data](https://web.stanford.edu/~rezab/nips2014workshop/submits/logmat.pdf)

## Setup the dataset

In [22]:
df_matrix_mf = df.copy()
df_matrix_mf = df_matrix_mf[df["type"] == "top_track"]
df_matrix_mf["username"] = df_matrix_mf["username"].astype("category")
df_matrix_mf["id"] = df_matrix_mf["id"].astype("category")
df_matrix_mf[["username", "id", "affinity"] + spoti.NUMERICAL_FEATURES]
df_matrix_mf["affinity"] *= 100
df_matrix_mf["affinity"]

0        50.0
1        49.0
2        48.0
3        47.0
4        46.0
         ...
12318     1.0
12319     0.8
12320     0.6
12321     0.4
12322     0.2
Name: affinity, Length: 1200, dtype: float64

In [23]:
# Create the matrix dataset
class MatrixDataset:
    _matrix: np.ndarray

    @property
    def matrix(self) -> np.ndarray:
        return self._matrix

    def __init__(self, num_users: int, num_items: int):
        # A matrix of shape (num_users, num_items)
        self._matrix = np.zeros((num_users, num_items))

    def add_interaction(self, user_id: int, item_id: int, value: float):
        """
        Adds a new interaction to the matrix.
        :param user_id: The user id.
        :param item_id: The item id.
        :param value: The value of the interaction.
        """
        self._matrix[user_id, item_id] = value

    def fill_from_df(self, users: pd.Series, items: pd.Series, values: pd.Series):
        """
        Fills the matrix from a dataframe.
        :param df: The dataframe.
        :param user_col: The user column.
        :param item_col: The item column.
        :param value_col: The value column.
        """
        assert (
            len(users) == len(items) == len(values)
        ), "The length of the users, items and values must be the same."

        for user, item, value in zip(users, items, values):
            self.add_interaction(user, item, value)

    def __str__(self):
        return str(self._matrix)

In [24]:
num_users = len(df_matrix_mf["username"].unique())
num_items = len(df_matrix_mf["id"].unique())

In [25]:
matrix_mf = MatrixDataset(num_users, num_items)
matrix_mf.fill_from_df(df_matrix_mf["username"].cat.codes, df_matrix_mf["id"].cat.codes, df_matrix_mf["affinity"])
R = matrix_mf.matrix
R

array([[ 0. ,  0. , 62. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 54. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 4.4, 30. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ..., 46. ,  0. ,  0. ]])

In [26]:
def convert_to_ids(values: List[str], column: str) -> List[int]:
    """
    Gets the user ids from the usernames.
    :param usernames: The usernames.
    :return: The user ids.
    """
    return df_matrix_mf[df_matrix_mf[column].isin(values)][column].cat.codes.tolist()

def retrieve_value_from_ids(ids: List[int], column: str) -> str:
    """
    Gets the value from the ids.
    :param ids: The ids.
    :return: The value.
    """
    return df_matrix_mf[df_matrix_mf[column].cat.codes.isin(ids)][column].tolist()

def get_df_rows_from_ids(ids: List[int], column: str, search_in: pd.DataFrame) -> pd.DataFrame:
    """
    Gets the dataframe rows from the ids.
    :param ids: The ids.
    :return: The dataframe rows.
    """
    return search_in[search_in[column].cat.codes.isin(ids)]

In [27]:
# Create a matrix U that contains the index that sorts the users by their affinity
I = np.argsort(matrix_mf.matrix, axis=1)
I.shape

(8, 923)

In [28]:
def compute_alpha(matrix: np.ndarray) -> np.ndarray:
    """
    Computes the alpha matrix.
    :param matrix: The matrix.
    :param k: The number of neighbors.
    :return: The alpha matrix.
    """
    num_items = matrix.shape[1] * matrix.shape[0]
    sum_matrix = matrix.flatten().sum()
    number_of_zeros = num_items - np.count_nonzero(matrix)
    alpha = number_of_zeros / sum_matrix
    return alpha

alpha = compute_alpha(matrix_mf.matrix)
print(alpha)
R *= alpha
R

0.264317361339022

array([[ 0.        ,  0.        , 16.3876764 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 14.27313751],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.16299639,  7.92952084,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ..., 12.15859862,
         0.        ,  0.        ]])

_Let $l_{u,i}$ denote the event that user $u$ has chosen to interact with item $i$ (user $u$ prefers item $i$). Then, we can let the probability of this event occurring be distributed according to a logistic function parameterized by the sum of the inner product of user and item latent factor vectors and user and item biases._
$$
p(l_{ui} | x_u, y_i, \beta_i, \beta_j) = \frac{\exp(x_uy_i^T + \beta_u + \beta_i)}{1 + \exp(x_uy_i^T + \beta_u + \beta_i)}
$$

The log posterior probability of $x_u, y_i, \beta_u, \beta_i$ given the observed data $\mathbf{R}$ is given by:
$$
\log p(\mathbf{X}, \mathbf{Y}, \beta | \mathbf{R}) = \sum_{u,i} \alpha r_{ui} (x_u^T y_i + \beta_u + \beta_i) - (1 + \alpha r_{ui}) \log(1 + \exp(x_u^T y_i + \beta_u + \beta_i)) - \frac{\lambda}{2} ||x_u||^2 - \frac{\lambda}{2} ||y_i||^2
$$

In [29]:
def log_posterior(
    X: torch.Tensor,
    Y: torch.Tensor,
    beta_u: torch.Tensor,
    beta_i: torch.Tensor,
    R: torch.Tensor,
    alpha: float,
    lambd: float,
) -> torch.Tensor:
    """
    Computes the log posterior of the model, which is:
    :param X: The latent vectors of the users.
    :param Y: The latent vectors of the items.
    :param beta_u: The bias of the users.
    :param beta_i: The bias of the items.
    :param R: The matrix of interactions.
    :param alpha: The alpha parameter.
    :param lambd: The lambda parameter.
    :return: The log posterior.
    """
    # Compute the first term
    term1 = alpha * R * (torch.matmul(X, Y.t()) + beta_u[:, None] + beta_i)
    term2 = (1 + alpha * R) * torch.log1p(torch.exp(torch.matmul(X, Y.t()) + beta_u[:, None] + beta_i))
    regularization = (lambd / 2) * (torch.norm(X, p=2) ** 2 + torch.norm(Y, p=2) ** 2)
    return torch.sum(term1 - term2) - regularization

In [30]:
def mpr(I: torch.Tensor, R: torch.Tensor) -> float:
    """
    Compute the Mean Percentile Ranking (MPR) using a sorted index matrix.

    :param I: Matrix of sorted indices of items for each user.
    :param R: Rating or interaction matrix.
    :return: MPR value.
    """
    num_users, num_items = R.shape
    total_interactions = torch.sum(R)

    # Initialize MPR
    mpr = 0.0

    # Iterate over each user
    for u in range(num_users):
        # Get the indices of the items in sorted order for this user
        sorted_indices = I[u]

        # Calculate the rank for each item
        for i in range(num_items):
            item_index = sorted_indices[i]
            rank = i / num_items  # Percentile rank
            mpr += R[u, item_index] * rank

    # Normalize by the total number of interactions
    mpr /= total_interactions

    return mpr

In [31]:
def compute_predictions(
    X: torch.Tensor,
    Y: torch.Tensor,
    beta_u: torch.Tensor,
    beta_i: torch.Tensor,
) -> torch.Tensor:
    """
    Computes the predictions of the model.
    :param X: The latent vectors of the users.
    :param Y: The latent vectors of the items.
    :param beta_u: The bias of the users.
    :param beta_i: The bias of the items.
    :param R: The matrix of interactions.
    :return: The predictions.
    """
    return torch.matmul(X, Y.t()) + beta_u[:, None] + beta_i

In [32]:
def train(
    num_latent: int,
    lambd: float,
    alpha: float,
    learning_rate: float,
    epochs: int,
):
    """
    Trains the model.
    :param num_latent: The number of latent factors.
    :param lambd: The lambda parameter.
    :param alpha: The alpha parameter.
    :param learning_rate: The learning rate.
    :param epochs: The number of epochs.
    """
    mprs = []  # Record MPRs for each epoch

    # Initialize user and item latent factor matrices and bias vectors
    R = torch.tensor(matrix_mf.matrix, dtype=torch.float32)
    X = torch.randn(num_users, num_latent, requires_grad=True)
    Y = torch.randn(num_items, num_latent, requires_grad=True)
    beta_u = torch.randn(num_users, requires_grad=True)
    beta_i = torch.randn(num_items, requires_grad=True)

    # The objective is to minimize the negative log posterior
    optimizer = optim.Adagrad([X, Y, beta_u, beta_i], lr=learning_rate)

    # Training loop
    for epoch in tqdm(range(epochs)):
        # Zero out gradients
        optimizer.zero_grad()

        # Compute the loss
        loss = -log_posterior(X, Y, beta_u, beta_i, R, alpha, lambd)

        # Backpropagate
        loss.backward()

        # Update the parameters
        optimizer.step()

        # Make predictions
        predictions = compute_predictions(X, Y, beta_u, beta_i)

        # Compute MPR
        I = torch.argsort(predictions, descending=True, dim=1)
        mpr_value = mpr(I, R)

        # Record MPR
        mprs.append(mpr_value)

        # Print progress
        print(f"Epoch {epoch + 1} - Loss: {loss.item():.4f} - MPR: {mpr_value:.4f}")

    return X, Y, beta_u, beta_i, mprs

In [33]:
num_latent = 10
X, Y, beta_u, beta_i, mprs = train(
    num_latent=num_latent,
    lambd=0.1,
    alpha=alpha,
    learning_rate=0.1,
    epochs=100,
)

  2%|▏         | 2/100 [00:00<00:06, 14.52it/s]

Epoch 1 - Loss: 13199.3457 - MPR: 0.4532
Epoch 2 - Loss: 10517.6914 - MPR: 0.4199

  4%|▍         | 4/100 [00:00<00:05, 16.31it/s]

Epoch 3 - Loss: 9093.4580 - MPR: 0.3899
Epoch 4 - Loss: 8121.9048 - MPR: 0.3632

  6%|▌         | 6/100 [00:00<00:05, 16.96it/s]

Epoch 5 - Loss: 7390.0474 - MPR: 0.3382
Epoch 6 - Loss: 6809.0278 - MPR: 0.3149

  8%|▊         | 8/100 [00:00<00:05, 17.22it/s]

Epoch 7 - Loss: 6332.4590 - MPR: 0.2932
Epoch 8 - Loss: 5932.7520 - MPR: 0.2731

 10%|█         | 10/100 [00:00<00:05, 17.33it/s]

Epoch 9 - Loss: 5592.0596 - MPR: 0.2550
Epoch 10 - Loss: 5298.0830 - MPR: 0.2378

 12%|█▏        | 12/100 [00:00<00:05, 17.57it/s]

Epoch 11 - Loss: 5041.9170 - MPR: 0.2222
Epoch 12 - Loss: 4816.8735 - MPR: 0.2074

 14%|█▍        | 14/100 [00:00<00:04, 17.61it/s]

Epoch 13 - Loss: 4617.7764 - MPR: 0.1941
Epoch 14 - Loss: 4440.5317 - MPR: 0.1820

 16%|█▌        | 16/100 [00:00<00:04, 17.75it/s]

Epoch 15 - Loss: 4281.8486 - MPR: 0.1710
Epoch 16 - Loss: 4139.0483 - MPR: 0.1607

 18%|█▊        | 18/100 [00:01<00:04, 17.78it/s]

Epoch 17 - Loss: 4009.9277 - MPR: 0.1512
Epoch 18 - Loss: 3892.6621 - MPR: 0.1424

 20%|██        | 20/100 [00:01<00:04, 17.84it/s]

Epoch 19 - Loss: 3785.7275 - MPR: 0.1345
Epoch 20 - Loss: 3687.8440 - MPR: 0.1272

 22%|██▏       | 22/100 [00:01<00:04, 17.95it/s]

Epoch 21 - Loss: 3597.9292 - MPR: 0.1205
Epoch 22 - Loss: 3515.0640 - MPR: 0.1144

 24%|██▍       | 24/100 [00:01<00:04, 18.00it/s]

Epoch 23 - Loss: 3438.4609 - MPR: 0.1090
Epoch 24 - Loss: 3367.4460 - MPR: 0.1040

 26%|██▌       | 26/100 [00:01<00:04, 18.11it/s]

Epoch 25 - Loss: 3301.4355 - MPR: 0.0993
Epoch 26 - Loss: 3239.9248 - MPR: 0.0951

 28%|██▊       | 28/100 [00:01<00:03, 18.03it/s]

Epoch 27 - Loss: 3182.4727 - MPR: 0.0911
Epoch 28 - Loss: 3128.6951 - MPR: 0.0875

 30%|███       | 30/100 [00:01<00:03, 18.16it/s]

Epoch 29 - Loss: 3078.2534 - MPR: 0.0841
Epoch 30 - Loss: 3030.8479 - MPR: 0.0810

 32%|███▏      | 32/100 [00:01<00:03, 18.27it/s]

Epoch 31 - Loss: 2986.2148 - MPR: 0.0780
Epoch 32 - Loss: 2944.1191 - MPR: 0.0753

 34%|███▍      | 34/100 [00:01<00:03, 18.10it/s]

Epoch 33 - Loss: 2904.3499 - MPR: 0.0729
Epoch 34 - Loss: 2866.7205 - MPR: 0.0706

 36%|███▌      | 36/100 [00:02<00:03, 17.75it/s]

Epoch 35 - Loss: 2831.0610 - MPR: 0.0684
Epoch 36 - Loss: 2797.2219 - MPR: 0.0663

 38%|███▊      | 38/100 [00:02<00:03, 17.93it/s]

Epoch 37 - Loss: 2765.0642 - MPR: 0.0644
Epoch 38 - Loss: 2734.4651 - MPR: 0.0626

 40%|████      | 40/100 [00:02<00:03, 18.08it/s]

Epoch 39 - Loss: 2705.3132 - MPR: 0.0610
Epoch 40 - Loss: 2677.5063 - MPR: 0.0594

 42%|████▏     | 42/100 [00:02<00:03, 18.05it/s]

Epoch 41 - Loss: 2650.9521 - MPR: 0.0581
Epoch 42 - Loss: 2625.5664 - MPR: 0.0568

 44%|████▍     | 44/100 [00:02<00:03, 17.88it/s]

Epoch 43 - Loss: 2601.2722 - MPR: 0.0555
Epoch 44 - Loss: 2577.9998 - MPR: 0.0543

 46%|████▌     | 46/100 [00:02<00:03, 17.81it/s]

Epoch 45 - Loss: 2555.6841 - MPR: 0.0532
Epoch 46 - Loss: 2534.2666 - MPR: 0.0522

 48%|████▊     | 48/100 [00:02<00:02, 17.47it/s]

Epoch 47 - Loss: 2513.6931 - MPR: 0.0512
Epoch 48 - Loss: 2493.9136 - MPR: 0.0502

 50%|█████     | 50/100 [00:02<00:03, 16.48it/s]

Epoch 49 - Loss: 2474.8823 - MPR: 0.0493
Epoch 50 - Loss: 2456.5564 - MPR: 0.0485

 52%|█████▏    | 52/100 [00:02<00:02, 16.93it/s]

Epoch 51 - Loss: 2438.8970 - MPR: 0.0477
Epoch 52 - Loss: 2421.8677 - MPR: 0.0470

 54%|█████▍    | 54/100 [00:03<00:02, 17.39it/s]

Epoch 53 - Loss: 2405.4348 - MPR: 0.0463
Epoch 54 - Loss: 2389.5671 - MPR: 0.0457

 56%|█████▌    | 56/100 [00:03<00:02, 17.73it/s]

Epoch 55 - Loss: 2374.2358 - MPR: 0.0450
Epoch 56 - Loss: 2359.4136 - MPR: 0.0445

 58%|█████▊    | 58/100 [00:03<00:02, 17.99it/s]

Epoch 57 - Loss: 2345.0752 - MPR: 0.0439
Epoch 58 - Loss: 2331.1970 - MPR: 0.0434

 60%|██████    | 60/100 [00:03<00:02, 18.18it/s]

Epoch 59 - Loss: 2317.7573 - MPR: 0.0428
Epoch 60 - Loss: 2304.7356 - MPR: 0.0423

 62%|██████▏   | 62/100 [00:03<00:02, 18.35it/s]

Epoch 61 - Loss: 2292.1125 - MPR: 0.0418
Epoch 62 - Loss: 2279.8699 - MPR: 0.0414

 64%|██████▍   | 64/100 [00:03<00:01, 18.42it/s]

Epoch 63 - Loss: 2267.9910 - MPR: 0.0409
Epoch 64 - Loss: 2256.4597 - MPR: 0.0405

 66%|██████▌   | 66/100 [00:03<00:01, 17.06it/s]

Epoch 65 - Loss: 2245.2615 - MPR: 0.0401
Epoch 66 - Loss: 2234.3811 - MPR: 0.0397

 68%|██████▊   | 68/100 [00:03<00:01, 17.18it/s]

Epoch 67 - Loss: 2223.8066 - MPR: 0.0394
Epoch 68 - Loss: 2213.5247 - MPR: 0.0390

 70%|███████   | 70/100 [00:03<00:01, 16.88it/s]

Epoch 69 - Loss: 2203.5237 - MPR: 0.0387
Epoch 70 - Loss: 2193.7920 - MPR: 0.0383

 72%|███████▏  | 72/100 [00:04<00:01, 17.24it/s]

Epoch 71 - Loss: 2184.3201 - MPR: 0.0380
Epoch 72 - Loss: 2175.0967 - MPR: 0.0377

 74%|███████▍  | 74/100 [00:04<00:01, 17.50it/s]

Epoch 73 - Loss: 2166.1128 - MPR: 0.0374
Epoch 74 - Loss: 2157.3591 - MPR: 0.0372

 76%|███████▌  | 76/100 [00:04<00:01, 17.70it/s]

Epoch 75 - Loss: 2148.8276 - MPR: 0.0369
Epoch 76 - Loss: 2140.5098 - MPR: 0.0366

 78%|███████▊  | 78/100 [00:04<00:01, 17.87it/s]

Epoch 77 - Loss: 2132.3977 - MPR: 0.0364
Epoch 78 - Loss: 2124.4841 - MPR: 0.0361

 80%|████████  | 80/100 [00:04<00:01, 17.98it/s]

Epoch 79 - Loss: 2116.7620 - MPR: 0.0359
Epoch 80 - Loss: 2109.2246 - MPR: 0.0357

 82%|████████▏ | 82/100 [00:04<00:00, 18.01it/s]

Epoch 81 - Loss: 2101.8657 - MPR: 0.0355
Epoch 82 - Loss: 2094.6790 - MPR: 0.0353

 84%|████████▍ | 84/100 [00:04<00:00, 17.43it/s]

Epoch 83 - Loss: 2087.6587 - MPR: 0.0351
Epoch 84 - Loss: 2080.7993 - MPR: 0.0349

 86%|████████▌ | 86/100 [00:04<00:00, 17.51it/s]

Epoch 85 - Loss: 2074.0952 - MPR: 0.0347
Epoch 86 - Loss: 2067.5415 - MPR: 0.0345

 88%|████████▊ | 88/100 [00:04<00:00, 17.71it/s]

Epoch 87 - Loss: 2061.1338 - MPR: 0.0343
Epoch 88 - Loss: 2054.8665 - MPR: 0.0342

 90%|█████████ | 90/100 [00:05<00:00, 17.86it/s]

Epoch 89 - Loss: 2048.7358 - MPR: 0.0340
Epoch 90 - Loss: 2042.7372 - MPR: 0.0338

 92%|█████████▏| 92/100 [00:05<00:00, 18.03it/s]

Epoch 91 - Loss: 2036.8666 - MPR: 0.0337
Epoch 92 - Loss: 2031.1198 - MPR: 0.0335

 94%|█████████▍| 94/100 [00:05<00:00, 18.13it/s]

Epoch 93 - Loss: 2025.4935 - MPR: 0.0334
Epoch 94 - Loss: 2019.9839 - MPR: 0.0332

 96%|█████████▌| 96/100 [00:05<00:00, 18.16it/s]

Epoch 95 - Loss: 2014.5874 - MPR: 0.0331
Epoch 96 - Loss: 2009.3009 - MPR: 0.0330

 98%|█████████▊| 98/100 [00:05<00:00, 18.22it/s]

Epoch 97 - Loss: 2004.1208 - MPR: 0.0328
Epoch 98 - Loss: 1999.0441 - MPR: 0.0327

100%|██████████| 100/100 [00:05<00:00, 17.72it/s]

Epoch 99 - Loss: 1994.0679 - MPR: 0.0326
Epoch 100 - Loss: 1989.1895 - MPR: 0.0325

In [34]:
px.line(y=mprs, title="MPR over epochs")

In [35]:
user_latent = X.detach().numpy()
item_latent = Y.detach().numpy()

if num_latent <= 3:
    # Add the latent vectors to the dataframe
    df_matrix_mf["user_latent"] = df_matrix_mf["username"].cat.codes.apply(
        lambda x: user_latent[x]
    )
    df_matrix_mf["item_latent"] = df_matrix_mf["id"].cat.codes.apply(
        lambda x: item_latent[x]
    )

    # Add the biases to the dataframe
    df_matrix_mf["user_bias"] = df_matrix_mf["username"].cat.codes.apply(
        lambda x: beta_u[x].item()
    )
    df_matrix_mf["item_bias"] = df_matrix_mf["id"].cat.codes.apply(
        lambda x: beta_i[x].item()
    )

    for i in range(num_latent):
        df_matrix_mf[f"user_latent_{i}"] = df_matrix_mf["user_latent"].apply(lambda x: x[i])
        df_matrix_mf[f"latent_{i}"] = df_matrix_mf["item_latent"].apply(lambda x: x[i])

    fig = plotting.plot_latent_space(
        df_matrix_mf,
        color=df_matrix_mf["username"],
        text=df_matrix_mf["username"],
        title="User latent space",
        latent_columns=["latent_0", "latent_1", "latent_2"],
    )
    fig.show()

    df_user_latent = df_matrix_mf.drop_duplicates(subset=["username"])
    fig = plotting.plot_latent_space(
        df_user_latent,
        color=df_user_latent["username"],
        text=df_user_latent["username"],
        title="User latent space",
        latent_columns=["user_latent_0", "user_latent_1", "user_latent_2"],
    )
    fig.show()

In [44]:
# Choose a user
user = "jaslkh"
user_id = convert_to_ids([user], "username")[0]

# Make predictions for the user
predictions = compute_predictions(X, Y, beta_u, beta_i)

# Get the top N predictions
N = 300
I = torch.argsort(predictions[user_id], descending=True)[:N]
I = I.detach().numpy()

# Get the top 10 predictions
top_predictions = get_df_rows_from_ids(I, "id", df_matrix_mf)
top_predictions[["id"] + spoti.PRETTY_PRINT_FEATURES][130:].head(50)

,id,username,artists_names,name,release_year,popularity,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,tempo,loudness,duration_ms,release_year,popularity
134,4ffoWIfe9UWfyuJT5I0I7L,jaslkh,Johan Papaconstantino,Les mots bleus,2019,58,0.790,0.484,0.1140,0.271000,0.012900,0.1270,0.4310,171.988,-8.267,250893,2019,58
136,38VyljyWXnVxtYWSiH5Hzc,jaslkh,Ahmed Spins,Anchor Point,2022,1,0.681,0.787,0.0354,0.390000,0.532000,0.0928,0.3900,123.025,-9.800,359024,2022,1
137,0vrDGR5ZjdDIBUuDep6yXT,jaslkh,anees,leave me,2022,66,0.669,0.697,0.2280,0.093400,0.000000,0.0864,0.5350,78.709,-6.299,220539,2022,66
146,25xa84ZW8Wy3cHvRUzpvrY,jaslkh,Mandragora,Slytherin,2020,54,0.729,0.406,0.0822,0.109000,0.565000,0.2700,0.0388,163.998,-8.831,210731,2020,54
147,34LI7rwi9H8w2S5KTHnv1M,jaslkh,Manuel Turizo,Quiéreme Mientras Se Pueda,2020,68,0.793,0.782,0.0582,0.447000,0.000000,0.1240,0.8100,143.860,-3.945,191945,2020,68
1505,4yXKLDrHYrffSVmQOFdbDA,owen,Mom Jeans.,Scott Pilgrim vs. My GPA,2016,58,0.296,0.494,0.0370,0.071500,0.050700,0.1080,0.1750,163.669,-10.490,239597,2016,58
1506,141alNiSd9vG4Lb22BLHWM,owen,Mom Jeans.,What's Up?,2022,60,0.512,0.933,0.0413,0.000109,0.000199,0.2740,0.8280,84.488,-5.598,141908,2022,60
1507,19aUuDd6udp1ACNo9t3IuZ,owen,Mom Jeans.,Death Cup,2016,62,0.353,0.749,0.0411,0.092600,0.000553,0.1660,0.5740,85.983,-9.339,276000,2016,62
1508,1AMADyXgIWayh5vXLZo2qF,owen,Basement,Covet,2012,78,0.428,0.799,0.0468,0.001390,0.074200,0.0788,0.2280,139.052,-6.265,227340,2012,78
1509,73NKI74L085oOkIxyY9sJ1,owen,Basement,Covet - alt version,2022,48,0.556,0.471,0.0256,0.001420,0.000029,0.0799,0.2990,76.516,-7.444,198038,2022,48
1512,2PIcAQiSOayFwJrfWc72Qc,owen,Wolf Alice,Bros,2015,61,0.583,0.921,0.0697,0.003770,0.462000,0.2260,0.2220,125.980,-8.383,224720,2015,61
1514,5UWwZ5lm5PKu6eKsHAGxOk,owen,Foo Fighters,Everlong,1997,87,0.413,0.881,0.0367,0.000060,0.000308,0.0805,0.3640,158.066,-5.541,250546,1997,87
1517,5bwxMo2sye4bffTgp7uNbo,owen,Turnover,Take My Head,2015,59,0.316,0.859,0.0359,0.219000,0.141000,0.1020,0.3550,160.928,-6.982,193911,2015,59
1518,4wFeMmJDlgkAxlQ07PbdGZ,owen,Elita,Sour Switchblade,2021,67,0.533,0.865,0.0300,0.040500,0.927000,0.1060,0.8600,109.987,-5.168,148955,2021,67
1519,7dJYggqjKo71KI9sLzqCs8,owen,Doja Cat,Agora Hills,2023,91,0.750,0.674,0.0970,0.228000,0.000089,0.1220,0.3920,123.026,-6.128,265360,2023,91
1520,1JgknGBbrfmEHeOZH051SS,owen,SUICIDAL-IDOL,ecstacy (slowed),2023,90,0.551,0.677,0.0665,0.017300,0.000000,0.3810,0.1950,106.414,-7.311,119120,2023,90
1522,2XYao6mmiycQEpNFG4Mu9b,owen,BabySolo33,LnlyBby,2022,30,0.708,0.300,0.0752,0.410000,0.320000,0.1030,0.2600,95.018,-12.861,174147,2022,30
1523,19GeonlE0aghbDJosYyMwn,owen,BabySolo33,BFF <3,2022,28,0.845,0.280,0.1410,0.295000,0.001040,0.0896,0.5270,120.031,-12.457,193654,2022,28
1524,1vkADCsLVzMk5NwmTk3DVI,owen,BabySolo33,Balayette,2021,36,0.723,0.691,0.0704,0.199000,0.000886,0.0983,0.2250,116.010,-8.706,124000,2021,36
1528,4fcS09l483Cl6JvJScziYN,owen,betcover!!,海豚少年 - アルバムバージョン,2019,21,0.681,0.708,0.0912,0.117000,0.011000,0.1000,0.3240,100.386,-7.375,293733,2019,21
1529,1Y1L17diqOw77eTSBselGS,owen,betcover!!,異星人,2019,29,0.547,0.470,0.0346,0.369000,0.003760,0.1090,0.1560,169.916,-8.546,361520,2019,29
1533,4yGb9rMRsKO07gvffTSBg1,owen,YG Pablo,22h22,2023,60,0.737,0.506,0.1310,0.747000,0.000130,0.1020,0.3200,129.910,-11.587,191066,2023,60
1534,1jLkZPtil9VQTkMzgq0017,owen,MCR-T,1-800-GHETTOLICIOUS,2023,46,0.875,0.837,0.1480,0.001430,0.045200,0.1450,0.8140,136.994,-8.386,262773,2023,46
1535,4sOX1nhpKwFWPvoMMExi3q,owen,MARINA,Primadonna,2012,75,0.660,0.689,0.0337,0.088400,0.000000,0.0922,0.4270,127.980,-2.671,221075,2012,75
1536,7FuyZvm8Bc4Cb56KPwWFpc,owen,Mietze Conte,bunnybunnybunny,2022,52,0.763,0.637,0.0530,0.192000,0.878000,0.3070,0.5120,99.473,-7.105,88040,2022,52
1537,5ORPYXJKlpHWIdceavSGrL,owen,ASIAN KUNG-FU GENERATION,遥か彼方,2012,68,0.308,0.955,0.1110,0.000024,0.113000,0.1660,0.2370,174.991,-3.763,243346,2012,68
1538,4tRhRLBxIZ34Iw0eCuiC03,owen,southstar,Miss You,2022,73,0.663,0.559,0.0391,0.136000,0.089400,0.1080,0.2960,145.007,-12.876,206019,2022,73
1539,3NfqN997u9A3YAAafgzhIa,owen,Pixies,All I Think About Now,2016,70,0.251,0.575,0.0311,0.004050,0.001350,0.1500,0.2180,185.731,-7.819,187320,2016,70
1545,75H2BlVa1kzYvQznPOzD33,owen,Cinco,G13,2022,46,0.599,0.536,0.1120,0.418000,0.000000,0.2310,0.6710,105.160,-9.528,150000,2022,46
1551,2M2YBN8AvH6FQJC0IsLErX,owen,Dosseh,Macabre,2023,56,0.815,0.648,0.3030,0.559000,0.000000,0.1080,0.7070,140.043,-6.465,208841,2023,56
1553,6qvyN6NTUpdfOJRYjtSSd7,owen,Josman,Intro,2022,72,0.755,0.636,0.2810,0.324000,0.000000,0.0717,0.5230,144.953,-6.529,147720,2022,72
1554,3ySqZ8yGoh4Emi9HiPCCdP,owen,Lil Uzi Vert,Werewolf (feat. Bring Me The Horizon),2023,69,0.389,0.962,0.2480,0.000060,0.623000,0.3310,0.1550,183.049,-4.772,239863,2023,69
1555,4yGb9rMRsKO07gvffTSBg1,owen,YG Pablo,22h22,2023,60,0.737,0.506,0.1310,0.747000,0.000130,0.1020,0.3200,129.910,-11.587,191066,2023,60
1556,4fcS09l483Cl6JvJScziYN,owen,betcover!!,海豚少年 - アルバムバージョン,2019,21,0.681,0.708,0.0912,0.117000,0.011000,0.1000,0.3240,100.386,-7.375,293733,2019,21
1558,3NfqN997u9A3YAAafgzhIa,owen,Pixies,All I Think About Now,2016,70,0.251,0.575,0.0311,0.004050,0.001350,0.1500,0.2180,185.731,-7.819,187320,2016,70
1559,75H2BlVa1kzYvQznPOzD33,owen,Cinco,G13,2022,46,0.599,0.536,0.1120,0.418000,0.000000,0.2310,0.6710,105.160,-9.528,150000,2022,46
1561,2M2YBN8AvH6FQJC0IsLErX,owen,Dosseh,Macabre,2023,56,0.815,0.648,0.3030,0.559000,0.000000,0.1080,0.7070,140.043,-6.465,208841,2023,56
1562,1AMADyXgIWayh5vXLZo2qF,owen,Basement,Covet,2012,78,0.428,0.799,0.0468,0.001390,0.074200,0.0788,0.2280,139.052,-6.265,227340,2012,78
1563,6qvyN6NTUpdfOJRYjtSSd7,owen,Josman,Intro,2022,72,0.755,0.636,0.2810,0.324000,0.000000,0.0717,0.5230,144.953,-6.529,147720,2022,72
1565,1uBWiynww2fieq2m6vNlKd,owen,Josman,"Tulum, México",2023,59,0.854,0.440,0.4480,0.342000,0.000000,0.0951,0.3870,143.975,-9.109,255160,2023,59
1566,0xLWMbuXHlW2O1DouU57AK,owen,Saez,Jeune et con,1999,59,0.427,0.808,0.0647,0.001110,0.000000,0.7440,0.3300,102.893,-6.939,232973,1999,59
1567,2lWkBor4F6kWhBdBLaD9nU,owen,Saez,Pilule,2010,51,0.584,0.794,0.1680,0.227000,0.000034,0.0998,0.8400,163.059,-4.575,318905,2010,51
1568,1cnATC0mQNipvfoAbLScfb,owen,Saez,J'accuse,2010,54,0.743,0.712,0.0624,0.075900,0.000000,0.0785,0.8840,107.013,-5.018,268532,2010,54
1569,0Fcd9Z2ssUsVzoHmsGd1zu,owen,Saez,No Place For Us,2002,26,0.533,0.662,0.0586,0.017400,0.000003,0.2180,0.7270,154.493,-8.137,216053,2002,26
1573,141alNiSd9vG4Lb22BLHWM,owen,Mom Jeans.,What's Up?,2022,60,0.512,0.933,0.0413,0.000109,0.000199,0.2740,0.8280,84.488,-5.598,141908,2022,60
1574,19aUuDd6udp1ACNo9t3IuZ,owen,Mom Jeans.,Death Cup,2016,62,0.353,0.749,0.0411,0.092600,0.000553,0.1660,0.5740,85.983,-9.339,276000,2016,62
1575,4yXKLDrHYrffSVmQOFdbDA,owen,Mom Jeans.,Scott Pilgrim vs. My GPA,2016,58,0.296,0.494,0.0370,0.071500,0.050700,0.1080,0.1750,163.669,-10.490,239597,2016,58
1576,4i0y40eLTmexj9pCrCIkxF,owen,Baby B3ns,Herzcrash,2023,51,0.746,0.855,0.1800,0.173000,0.021000,0.1690,0.4560,156.070,-5.660,117523,2023,51
1577,0a0EYuSVqeVqV8kjN9bFYC,owen,Peach Pit,Techno Show,2018,59,0.605,0.724,0.0441,0.121000,0.431000,0.1080,0.8980,89.403,-7.729,226613,2018,59
1578,0Wl2RALqRacaIJhnlRHK8J,owen,Turnover,Cutting My Fingers Off,2015,58,0.419,0.665,0.0367,0.042100,0.067500,0.1250,0.2450,157.064,-7.868,195984,2015,58