In [1]:
import pandas as pd
from lib import spoti
from constants import data_path, users_list
import os

In [3]:
owen = spoti.SpotiUser("owen")
owen.get_auth_url()
owen.log_user()

In [4]:
PLAYLISTS = [
    "0iwMTcAhHhqjv3ytEfhWs7",
    "24P5rHoP6MhEiEaB25l1wI",
    "7E3uEa1emOcbZJuB8sFXeK",
    "0AVwU8BpO8p7MS5LeU8lmj",
    "6RCtJw3jv1MO3HFeeEY9hC",
    "2jqYP6k583TFLfejNZ2qhn",
    "7wFuDz4omYRgckUCFwY8eX",
    "5zwLw7HmUqTZAXwOTqIdqy"
]

In [5]:
df_playlists = pd.DataFrame()

In [6]:
# df_playlists = pd.read_json(os.path.join(DATA_PATH, "tracks.json"))

In [7]:
for playlist in PLAYLISTS:
    df_playlist = owen.get_playlist_tracks(playlist)
    df_playlists = pd.concat([df_playlists, df_playlist], ignore_index=True)
    print(f"Playlist {playlist} retrieved, with {len(df_playlist)} tracks")

df_playlist.reset_index(drop=True, inplace=True)
# remove duplicates
df_playlists.drop_duplicates(subset=["id"], inplace=True)
df_playlists["username"] = "Spotify"
df_playlists

Playlist 0iwMTcAhHhqjv3ytEfhWs7 retrieved, with 491 tracks
Playlist 24P5rHoP6MhEiEaB25l1wI retrieved, with 896 tracks
Playlist 7E3uEa1emOcbZJuB8sFXeK retrieved, with 266 tracks
Playlist 0AVwU8BpO8p7MS5LeU8lmj retrieved, with 154 tracks
Playlist 6RCtJw3jv1MO3HFeeEY9hC retrieved, with 201 tracks
Playlist 2jqYP6k583TFLfejNZ2qhn retrieved, with 1013 tracks
Playlist 7wFuDz4omYRgckUCFwY8eX retrieved, with 2283 tracks
Playlist 5zwLw7HmUqTZAXwOTqIdqy retrieved, with 2805 tracks

,album,artists,available_markets,disc_number,duration_ms,episode,explicit,external_ids,external_urls,href,...,instrumentalness,liveness,valence,tempo,type_features,uri_features,track_href,analysis_url,duration_ms_features,time_signature
0,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,251488,False,False,{'isrc': 'GBF088590110'},{'spotify': 'https://open.spotify.com/track/4R...,https://api.spotify.com/v1/tracks/4RvWPyQ5RL0a...,...,0.003890,0.1040,0.535,112.067,audio_features,spotify:track:4RvWPyQ5RL0ao9LPZeSouE,https://api.spotify.com/v1/tracks/4RvWPyQ5RL0a...,https://api.spotify.com/v1/audio-analysis/4RvW...,251489,4
1,"{'album_type': 'compilation', 'artists': [{'ex...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,256146,False,False,{'isrc': 'GBF088590112'},{'spotify': 'https://open.spotify.com/track/74...,https://api.spotify.com/v1/tracks/748yv6bb3l3C...,...,0.001280,0.0950,0.653,95.159,audio_features,spotify:track:748yv6bb3l3CcKS45a6SZ8,https://api.spotify.com/v1/tracks/748yv6bb3l3C...,https://api.spotify.com/v1/audio-analysis/748y...,256147,4
2,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",1,209106,False,False,{'isrc': 'GBUM71103440'},{'spotify': 'https://open.spotify.com/track/7n...,https://api.spotify.com/v1/tracks/7nhWtCc3v6Ve...,...,0.002410,0.1800,0.838,73.760,audio_features,spotify:track:7nhWtCc3v6Vem80gYPlppQ,https://api.spotify.com/v1/tracks/7nhWtCc3v6Ve...,https://api.spotify.com/v1/audio-analysis/7nhW...,209107,4
3,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",1,170786,False,False,{'isrc': 'GBUM71029609'},{'spotify': 'https://open.spotify.com/track/4v...,https://api.spotify.com/v1/tracks/4vhVDkSx9RSb...,...,0.011600,0.0706,0.550,118.829,audio_features,spotify:track:4vhVDkSx9RSb2k6mWFMYNI,https://api.spotify.com/v1/tracks/4vhVDkSx9RSb...,https://api.spotify.com/v1/audio-analysis/4vhV...,170787,4
4,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",1,264253,False,False,{'isrc': 'GBUM71029621'},{'spotify': 'https://open.spotify.com/track/5R...,https://api.spotify.com/v1/tracks/5RYLa5P4qweE...,...,0.002940,0.1280,0.703,130.128,audio_features,spotify:track:5RYLa5P4qweEAKq5U1gdcK,https://api.spotify.com/v1/tracks/5RYLa5P4qweE...,https://api.spotify.com/v1/audio-analysis/5RYL...,264253,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8104,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,208400,False,False,{'isrc': 'USKO11502353'},{'spotify': 'https://open.spotify.com/track/2w...,https://api.spotify.com/v1/tracks/2wS5yNEN2Bsw...,...,0.000000,0.0804,0.611,111.038,audio_features,spotify:track:2wS5yNEN2Bsw9smRBxBL6F,https://api.spotify.com/v1/tracks/2wS5yNEN2Bsw...,https://api.spotify.com/v1/audio-analysis/2wS5...,208400,4
8105,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,177569,False,False,{'isrc': 'QM24S2300334'},{'spotify': 'https://open.spotify.com/track/1g...,https://api.spotify.com/v1/tracks/1gOXJCXmQ7lV...,...,0.000002,0.0789,0.369,76.025,audio_features,spotify:track:1gOXJCXmQ7lVDdjxyHqfF4,https://api.spotify.com/v1/tracks/1gOXJCXmQ7lV...,https://api.spotify.com/v1/audio-analysis/1gOX...,177570,4
8106,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,187699,False,False,{'isrc': 'USUM72306520'},{'spotify': 'https://open.spotify.com/track/2u...,https://api.spotify.com/v1/tracks/2uqCJn5VFTf3...,...,0.000027,0.0551,0.883,115.010,audio_features,spotify:track:2uqCJn5VFTf3sZEDJZvvX0,https://api.spotify.com/v1/tracks/2uqCJn5VFTf3...,https://api.spotify.com/v1/audio-analysis/2uqC...,187699,4
8107,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,212013,False,True,{'isrc': 'USAT20402871'},{'spotify': 'https://open.spotify.com/track/5w...,https://api.spotify.com/v1/tracks/5wK87f6MxR78...,...,0.000000,0.1160,0.467,152.334,audio_features,spotify:track:5wK87f6MxR78H9XnnwkRQ5,https://api.spotify.com/v1/tracks/5wK87f6MxR78...,https://api.spotify.com/v1/audio-analysis/5wK8...,212013,4
8108,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,230066,False,False,{'isrc': 'CAN111500147'},{'spotify': 'https://open.spotify.com/track/1z...,https://api.spotify.com/v1/tracks/1zoXZMg1LxCB...,...,0.000000,0.0994,0.515,100.006,audio_features,spotify:track:1zoXZMg1LxCBqtodFAT1Nx,https://api.spotify.com/v1/tracks/1zoXZMg1LxCB...,https://api.spotify.com/v1/audio-analysis/1zoX...,230067,4

In [14]:
df_playlists.to_json(os.path.join(data_path.DATA_PATH, f"tracks.json"), orient="records")

In [15]:
df_playlists_loaded = pd.read_json(os.path.join(data_path.DATA_PATH, "tracks.json"))
df_playlists_loaded

,album,artists,available_markets,disc_number,duration_ms,episode,explicit,external_ids,external_urls,href,...,instrumentalness,liveness,valence,tempo,type_features,uri_features,track_href,analysis_url,duration_ms_features,time_signature
0,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,251488,False,False,{'isrc': 'GBF088590110'},{'spotify': 'https://open.spotify.com/track/4R...,https://api.spotify.com/v1/tracks/4RvWPyQ5RL0a...,...,0.003890,0.1040,0.535,112.067,audio_features,spotify:track:4RvWPyQ5RL0ao9LPZeSouE,https://api.spotify.com/v1/tracks/4RvWPyQ5RL0a...,https://api.spotify.com/v1/audio-analysis/4RvW...,251489,4
1,"{'album_type': 'compilation', 'artists': [{'ex...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,256146,False,False,{'isrc': 'GBF088590112'},{'spotify': 'https://open.spotify.com/track/74...,https://api.spotify.com/v1/tracks/748yv6bb3l3C...,...,0.001280,0.0950,0.653,95.159,audio_features,spotify:track:748yv6bb3l3CcKS45a6SZ8,https://api.spotify.com/v1/tracks/748yv6bb3l3C...,https://api.spotify.com/v1/audio-analysis/748y...,256147,4
2,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",1,209106,False,False,{'isrc': 'GBUM71103440'},{'spotify': 'https://open.spotify.com/track/7n...,https://api.spotify.com/v1/tracks/7nhWtCc3v6Ve...,...,0.002410,0.1800,0.838,73.760,audio_features,spotify:track:7nhWtCc3v6Vem80gYPlppQ,https://api.spotify.com/v1/tracks/7nhWtCc3v6Ve...,https://api.spotify.com/v1/audio-analysis/7nhW...,209107,4
3,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",1,170786,False,False,{'isrc': 'GBUM71029609'},{'spotify': 'https://open.spotify.com/track/4v...,https://api.spotify.com/v1/tracks/4vhVDkSx9RSb...,...,0.011600,0.0706,0.550,118.829,audio_features,spotify:track:4vhVDkSx9RSb2k6mWFMYNI,https://api.spotify.com/v1/tracks/4vhVDkSx9RSb...,https://api.spotify.com/v1/audio-analysis/4vhV...,170787,4
4,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",1,264253,False,False,{'isrc': 'GBUM71029621'},{'spotify': 'https://open.spotify.com/track/5R...,https://api.spotify.com/v1/tracks/5RYLa5P4qweE...,...,0.002940,0.1280,0.703,130.128,audio_features,spotify:track:5RYLa5P4qweEAKq5U1gdcK,https://api.spotify.com/v1/tracks/5RYLa5P4qweE...,https://api.spotify.com/v1/audio-analysis/5RYL...,264253,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7888,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,208400,False,False,{'isrc': 'USKO11502353'},{'spotify': 'https://open.spotify.com/track/2w...,https://api.spotify.com/v1/tracks/2wS5yNEN2Bsw...,...,0.000000,0.0804,0.611,111.038,audio_features,spotify:track:2wS5yNEN2Bsw9smRBxBL6F,https://api.spotify.com/v1/tracks/2wS5yNEN2Bsw...,https://api.spotify.com/v1/audio-analysis/2wS5...,208400,4
7889,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,177569,False,False,{'isrc': 'QM24S2300334'},{'spotify': 'https://open.spotify.com/track/1g...,https://api.spotify.com/v1/tracks/1gOXJCXmQ7lV...,...,0.000002,0.0789,0.369,76.025,audio_features,spotify:track:1gOXJCXmQ7lVDdjxyHqfF4,https://api.spotify.com/v1/tracks/1gOXJCXmQ7lV...,https://api.spotify.com/v1/audio-analysis/1gOX...,177570,4
7890,"{'album_type': 'single', 'artists': [{'externa...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,187699,False,False,{'isrc': 'USUM72306520'},{'spotify': 'https://open.spotify.com/track/2u...,https://api.spotify.com/v1/tracks/2uqCJn5VFTf3...,...,0.000027,0.0551,0.883,115.010,audio_features,spotify:track:2uqCJn5VFTf3sZEDJZvvX0,https://api.spotify.com/v1/tracks/2uqCJn5VFTf3...,https://api.spotify.com/v1/audio-analysis/2uqC...,187699,4
7891,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,212013,False,True,{'isrc': 'USAT20402871'},{'spotify': 'https://open.spotify.com/track/5w...,https://api.spotify.com/v1/tracks/5wK87f6MxR78...,...,0.000000,0.1160,0.467,152.334,audio_features,spotify:track:5wK87f6MxR78H9XnnwkRQ5,https://api.spotify.com/v1/tracks/5wK87f6MxR78...,https://api.spotify.com/v1/audio-analysis/5wK8...,212013,4
7892,"{'album_type': 'album', 'artists': [{'external...",[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,230066,False,False,{'isrc': 'CAN111500147'},{'spotify': 'https://open.spotify.com/track/1z...,https://api.spotify.com/v1/tracks/1zoXZMg1LxCB...,...,0.000000,0.0994,0.515,100.006,audio_features,spotify:track:1zoXZMg1LxCBqtodFAT1Nx,https://api.spotify.com/v1/tracks/1zoXZMg1LxCB...,https://api.spotify.com/v1/audio-analysis/1zoX...,230067,4